use std::any::Any;

use crate::beans::BeanContext;

/// Trait for beans that declare scheduled tasks.
///
/// Generated by `#[bean]` when `#[scheduled]` methods are present — the
/// bean-level counterpart of the `Controller::scheduled_tasks_boxed` wiring
/// that `#[routes]` emits for controllers.
///
/// # Example
///
/// ```ignore
/// #[bean]
/// impl CleanupService {
///     pub fn new(pool: SqlitePool) -> Self {
///         Self { pool }
///     }
///
///     #[scheduled(every = "5m")]
///     async fn purge_stale(&self) {
///         // periodic work
///     }
/// }
/// ```
///
/// Registration is automatic: `#[bean]` emits an `after_register` hook that
/// calls [`BeanRegistry::register_scheduled_source`], so `.register::<T>()`
/// alone is enough — `build_state()` collects the tasks from the resolved
/// graph and hands them to the scheduler's task registry (a warning is
/// logged when no `Scheduler` plugin is installed).
///
/// The tasks are type-erased as `Box<dyn Any + Send>` (double-boxed
/// `ScheduledTaskDef`s) so `r2e-core` needs no dependency on
/// `r2e-scheduler`; the scheduler's serve hook downcasts them via
/// `extract_tasks`, exactly like controller scheduled tasks.
///
/// [`BeanRegistry::register_scheduled_source`]: crate::beans::BeanRegistry::register_scheduled_source
pub trait ScheduledSource: Clone + Send + Sync + 'static {
    /// Build the type-erased scheduled task definitions for this bean.
    ///
    /// Called once against the resolved bean graph; each task captures a
    /// clone of the bean (read by type from the graph — an overridden
    /// *dependency* is honoured; pinning the scheduled bean itself skips its
    /// registration and drops the tasks, like `#[post_construct]`). The
    /// `ctx` parameter is unused by bean-generated impls today — it is part
    /// of the signature so the controller path can delegate here
    /// (interceptor sets are built from the graph).
    fn scheduled_tasks_boxed(&self, ctx: &BeanContext) -> Vec<Box<dyn Any + Send>>;
}
