//! The [`McpService`] trait — what `#[mcp_routes]` implements.

use std::sync::Arc;

use r2e_core::beans::BeanContext;
use r2e_core::config::{MissingKeyError, R2eConfig};

use crate::route::McpRoutes;

/// Trait for MCP tool services that can be registered with the R2E builder.
///
/// Implement this trait (typically via the `#[mcp_routes]` macro) to expose a
/// type's `#[tool]`/`#[resource]`/`#[prompt]` methods over the MCP
/// endpoint. The service core is constructed from the resolved bean graph by
/// type (see [`ContextConstruct`](r2e_core::ContextConstruct)) — once, at
/// registration; each route's dispatch closure clones an `Arc` of it per
/// call.
///
/// Services accumulate into the
/// [`McpServiceRegistry`](crate::registry::McpServiceRegistry), which the
/// [`McpServer`](crate::McpServer) plugin drains once when the router is
/// assembled. Any number of services share the single MCP endpoint; tool
/// and prompt names and resource URIs must be globally unique (a duplicate
/// is a boot panic naming both services).
///
/// # Example (generated by macro)
///
/// ```ignore
/// impl McpService for MathTools {
///     fn service_name() -> &'static str { "MathTools" }
///
///     fn routes(ctx: &Arc<BeanContext>) -> McpRoutes {
///         let wrapper = __R2eMcpMathTools {
///             core: Arc::new(<MathTools as ContextConstruct>::from_context(ctx)),
///             // plus prebuilt interceptor/guard sets when decorated
///         };
///         McpRoutes {
///             tools: vec![/* one ToolRoute per #[tool] method */],
///             resources: vec![/* … per #[resource] method */],
///             prompts: vec![/* … per #[prompt] method */],
///         }
///     }
/// }
/// ```
pub trait McpService: 'static {
    /// The service name (used in diagnostics and duplicate-tool errors).
    fn service_name() -> &'static str;

    /// Validate the config this service reads, in one aggregated report —
    /// the MCP peer of
    /// [`Controller::validate_config`](r2e_core::Controller::validate_config):
    /// the core's own `#[config]` keys plus every `#[intercept]`/`#[guard]`
    /// spec's declared keys. Called by `register_mcp_service`. The default
    /// reports nothing.
    fn validate_config(_config: &R2eConfig) -> Vec<MissingKeyError> {
        Vec::new()
    }

    /// Build this service's routes (tools, resources, prompts) from the
    /// resolved bean graph — one wrapper core, one set of prebuilt
    /// decorators, shared by every member's dispatch closure.
    fn routes(ctx: &Arc<BeanContext>) -> McpRoutes;
}
