use super::{ConfigError, R2eConfig};

/// The empty `Children` list for configs with no nested `#[config(section)]`
/// types.
///
/// This is the supported spelling for manual [`ConfigProperties`] impls —
/// use `type Children = NoChildren;` instead of reaching into
/// `r2e::type_list` internals.
pub type NoChildren = crate::type_list::TNil;

/// Metadata about a single configuration property.
#[derive(Debug, Clone)]
pub struct PropertyMeta {
    /// Relative key (e.g., `"pool_size"`).
    pub key: String,
    /// Absolute key (e.g., `"app.database.pool_size"`).
    pub full_key: String,
    /// Rust type name (e.g., `"i64"`).
    pub type_name: &'static str,
    /// Whether the property is required (no default and not `Option`).
    pub required: bool,
    /// Default value as a string, if any.
    pub default_value: Option<String>,
    /// Description from doc comments.
    pub description: Option<String>,
    /// Explicit environment variable name (from `#[config(env = "...")]`).
    pub env_var: Option<String>,
    /// Whether this property is a nested `#[config(section)]`.
    pub is_section: bool,
}

/// Trait for strongly-typed configuration sections.
///
/// Implement via `#[derive(ConfigProperties)]`:
///
/// ```ignore
/// #[derive(ConfigProperties, Clone, Debug)]
/// pub struct DatabaseConfig {
///     pub url: String,
///     #[config(default = 10)]
///     pub pool_size: i64,
///     pub timeout: Option<i64>,
/// }
///
/// let config = R2eConfig::from_yaml_str("app:\n  database:\n    url: postgres://localhost/mydb").unwrap();
/// let db = DatabaseConfig::from_config(&config, Some("app.database")).unwrap();
/// assert_eq!(db.pool_size, 10); // default applied
/// ```
///
/// Use `#[config(key = "...")]` to override the generated config key for a field.
/// This is useful when the YAML hierarchy doesn't match the Rust field name
/// (e.g., env var `OIDC_JWKS_URL` maps to `oidc.jwks.url`, not `oidc.jwks_url`):
///
/// ```ignore
/// #[derive(ConfigProperties, Clone, Debug)]
/// pub struct OidcConfig {
///     pub issuer: Option<String>,
///     #[config(key = "jwks.url")]
///     pub jwks_url: Option<String>,          // reads from "oidc.jwks.url" (with prefix "oidc")
///     #[config(key = "client.id", default = "my-app")]
///     pub client_id: String,                  // reads from "oidc.client.id"
/// }
/// ```
///
/// Nested sections with `#[config(section)]`:
///
/// ```ignore
/// #[derive(ConfigProperties, Clone, Debug)]
/// pub struct AppConfig {
///     pub name: String,
///     #[config(section)]
///     pub database: DatabaseConfig,  // reads from "app.database.*" (with prefix "app")
/// }
/// ```
///
/// See `r2e-core/tests/config.rs` for runnable examples.
///
/// # Manual implementations
///
/// When the derive cannot express a section's shape, a manual impl is
/// supported using only public API — [`NoChildren`], [`PropertyMeta`], and
/// `R2eConfig`'s prefix helpers (`has_prefix`, `sub_keys`):
///
/// ```ignore
/// impl ConfigProperties for MyDynamicConfig {
///     type Children = NoChildren;
///
///     fn from_config(config: &R2eConfig, prefix: Option<&str>) -> Result<Self, ConfigError> {
///         // custom parsing, e.g. driven by config.sub_keys(...)
///     }
/// }
/// ```
///
/// `properties_metadata` and `register_children` have default no-op bodies,
/// so a manual impl only needs `type Children` and `from_config`.
pub trait ConfigProperties: Sized {
    /// Type-level list of all nested `#[config(section)]` types (recursively flattened).
    ///
    /// Used by `load_config` to register children in the compile-time provision list `P`,
    /// so that `#[inject] config: ChildConfig` works without `#[config_section]`.
    ///
    /// Generated by `#[derive(ConfigProperties)]`. Leaf configs (no sections) default to `TNil`.
    type Children;

    /// Metadata about all expected properties.
    ///
    /// When `prefix` is `Some("app.database")`, `full_key` is `"app.database.pool_size"`.
    /// When `prefix` is `None`, `full_key` equals the relative key (`"pool_size"`).
    ///
    /// The default implementation returns no metadata — the derive generates
    /// a full override; manual impls may keep the default.
    fn properties_metadata(_prefix: Option<&str>) -> Vec<PropertyMeta> {
        Vec::new()
    }

    /// Construct from an `R2eConfig` instance using the given prefix.
    ///
    /// - `Some("app.database")` — keys are resolved as `"app.database.<field>"`.
    /// - `None` — keys are resolved at root level (`"<field>"`).
    fn from_config(config: &R2eConfig, prefix: Option<&str>) -> Result<Self, ConfigError>;

    /// Register nested `#[config(section)]` children as beans in the registry.
    ///
    /// The default implementation is a no-op. The `#[derive(ConfigProperties)]`
    /// macro generates an override that calls `registry.provide(child)` for each
    /// section field and recursively calls `register_children` on them.
    fn register_children(&self, _registry: &mut crate::beans::BeanRegistry) {}
}
