use super::typed::ConfigProperties;
use super::{ConfigError, R2eConfig};

/// Derive the `R2E_`-style env-var hint for a config key — but only when the
/// key is actually reachable through the env overlay.
///
/// `apply_env_overlay` maps `R2E_X_Y` → `x.y`
/// (only `_`→`.`), so it can never produce a dashed key. A kebab-case key such
/// as `database.min-idle` is therefore **not** addressable via any `R2E_` var
/// (`R2E_DATABASE_MIN_IDLE` would insert `database.min.idle`), and this returns
/// `None` so callers fall back to YAML-only wording. Dotted keys return their
/// `SCREAMING_SNAKE` env var.
pub(crate) fn derived_env_hint(key: &str) -> Option<String> {
    if key.contains('-') {
        None
    } else {
        Some(key.to_uppercase().replace('.', "_"))
    }
}

/// A single missing config key.
#[derive(Debug)]
pub struct MissingKeyError {
    /// Source that requires this key (bean name, controller name, section prefix).
    pub source: String,
    /// The config key that is missing.
    pub key: String,
    /// The expected type name.
    pub expected_type: String,
    /// Environment variable hint. `Some` only when the key is reachable via an
    /// `R2E_` env var; `None` for kebab-case keys (settable in YAML only).
    pub env_hint: Option<String>,
    /// Optional description (from `ConfigProperties` metadata).
    pub description: Option<String>,
}

impl std::fmt::Display for MissingKeyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "  - `{}`: key '{}' ({})",
            self.source, self.key, self.expected_type
        )?;
        match &self.env_hint {
            Some(hint) => write!(f, " — set env var `{}`", hint)?,
            None => write!(
                f,
                " — set '{}' in application.yaml (kebab-case keys are not addressable via R2E_ env vars)",
                self.key
            )?,
        }
        if let Some(desc) = &self.description {
            write!(f, " -- {}", desc)?;
        }
        Ok(())
    }
}

/// Aggregated config validation error.
#[derive(Debug)]
pub struct ConfigValidationError {
    pub errors: Vec<MissingKeyError>,
}

impl std::fmt::Display for ConfigValidationError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        writeln!(f, "Missing configuration keys:")?;
        for err in &self.errors {
            writeln!(f, "{}", err)?;
        }
        Ok(())
    }
}

impl std::error::Error for ConfigValidationError {}

/// Validate a list of config keys against an `R2eConfig`.
///
/// Each entry is `(source_name, key, type_name)`. Returns the list of
/// missing keys as [`MissingKeyError`]s (empty if all present).
pub fn validate_keys(config: &R2eConfig, keys: &[(&str, &str, &str)]) -> Vec<MissingKeyError> {
    keys.iter()
        .filter(|(_, key, _)| !config.contains_key(key))
        .map(|(source, key, type_name)| MissingKeyError {
            source: source.to_string(),
            key: key.to_string(),
            expected_type: type_name.to_string(),
            env_hint: derived_env_hint(key),
            description: None,
        })
        .collect()
}

/// Phase-1 missing-key walk for a `ConfigProperties` section.
///
/// Reports every missing required key — the section's own leaves plus, via
/// the derive-generated `PropertyMeta::validate_nested` hooks, every nested
/// `#[config(section)]`'s keys — with full per-property metadata. This walk
/// is metadata-only: it never calls `from_config`, so recursion does not
/// construct sections (no repeated secret resolution / deserialization).
/// [`validate_section`] adds the single top-level construction probe.
pub fn validate_section_keys<C: ConfigProperties>(
    config: &R2eConfig,
    prefix: Option<&str>,
) -> Vec<MissingKeyError> {
    let meta = C::properties_metadata(prefix);
    let source = prefix.unwrap_or("<root>");

    let mut errors: Vec<MissingKeyError> = meta
        .iter()
        .filter(|prop| prop.required && !prop.is_section)
        // The probe is generated by the derive next to `from_config` and is
        // the single owner of resolution semantics (config map, custom
        // `#[config(env = "VAR")]` var, any future source).
        .filter(|prop| !prop.is_resolvable(config))
        .map(|prop| MissingKeyError {
            source: source.to_string(),
            key: prop.full_key.clone(),
            expected_type: prop.type_name.to_string(),
            env_hint: match &prop.env_var {
                Some(env) => Some(env.clone()),
                None => derived_env_hint(&prop.full_key),
            },
            description: prop.description.clone(),
        })
        .collect();

    // Recurse into nested `#[config(section)]` properties. The hook is
    // generated by the derive next to `from_config` and owns the presence
    // semantics (mandatory → always, optional/defaulted → only when present,
    // map → per entry), so a nested section's missing required keys are all
    // reported here in phase 1 with full metadata instead of dying on the
    // phase-2 probe's first `NotFound`. `validate_nested` is `Some` only on
    // section properties.
    for prop in &meta {
        if let Some(validate) = prop.validate_nested {
            errors.extend(validate(config, prop));
        }
    }

    errors
}

/// Validate a `ConfigProperties` section against an `R2eConfig`.
///
/// Checks that all required keys are present (including nested
/// `#[config(section)]` keys, via [`validate_section_keys`]). Also attempts
/// to construct the section via `from_config` to detect type mismatches and
/// validation errors (e.g., garde constraints).
pub fn validate_section<C: ConfigProperties>(
    config: &R2eConfig,
    prefix: Option<&str>,
) -> Vec<MissingKeyError> {
    let source = prefix.unwrap_or("<root>");
    let mut errors = validate_section_keys::<C>(config, prefix);

    // If no missing keys, try constructing the section to surface
    // TypeMismatch and Validation errors. This is also the only reporting
    // path for manual `ConfigProperties` impls that keep the default (empty)
    // `properties_metadata` — the `NotFound` arm below stays live for them.
    if errors.is_empty() {
        if let Err(e) = C::from_config(config, prefix) {
            match e {
                ConfigError::TypeMismatch { key, expected } => {
                    errors.push(MissingKeyError {
                        source: source.to_string(),
                        key: key.clone(),
                        expected_type: expected.to_string(),
                        env_hint: derived_env_hint(&key),
                        description: Some(format!("type mismatch: expected {expected}")),
                    });
                }
                ConfigError::Validation(details) => {
                    for detail in details {
                        errors.push(MissingKeyError {
                            source: source.to_string(),
                            key: detail.key.clone(),
                            expected_type: "valid".to_string(),
                            env_hint: derived_env_hint(&detail.key),
                            description: Some(detail.message),
                        });
                    }
                }
                ConfigError::NotFound(key) => {
                    errors.push(MissingKeyError {
                        source: source.to_string(),
                        key: key.clone(),
                        expected_type: "unknown".to_string(),
                        env_hint: derived_env_hint(&key),
                        description: None,
                    });
                }
                ConfigError::Deserialize { key, message } => {
                    errors.push(MissingKeyError {
                        source: source.to_string(),
                        key: key.clone(),
                        expected_type: "deserializable".to_string(),
                        env_hint: derived_env_hint(&key),
                        description: Some(message),
                    });
                }
                ConfigError::Load(msg) => {
                    errors.push(MissingKeyError {
                        source: source.to_string(),
                        key: source.to_string(),
                        expected_type: "loadable".to_string(),
                        env_hint: derived_env_hint(source),
                        description: Some(msg),
                    });
                }
            }
        }
    }

    errors
}
