[package]
name = "example-mcp"
version = "0.1.0"
edition = "2021"
publish = false

[features]
dev-reload = ["r2e/dev-reload"]

[dependencies]
r2e = { path = "../../r2e", features = ["mcp"] }
schemars = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
r2e-test = { workspace = true }
serde_json = { workspace = true }
