//! gRPC server support for R2E.
//!
//! Provides gRPC service hosting with the same DX as HTTP controllers:
//! `#[inject]`, `#[config]`, guards, interceptors, and identity extraction.
//!
//! # Two transport modes
//!
//! - **Separate port**: gRPC on one port, HTTP on another.
//! - **Multiplexed**: both on the same port, routed by `content-type`.
//!
//! # Example
//!
//! ```ignore
//! use r2e_grpc::GrpcServer;
//!
//! AppBuilder::new()
//!     .plugin(GrpcServer::on_port("0.0.0.0:50051"))
//!     .build_state()
//!     .await
//!     .register_grpc_service::<UserGrpcService>()
//!     .serve("0.0.0.0:3000")
//! ```

pub mod guard;
pub mod identity;
pub mod multiplex;
pub mod registry;
pub mod server;
pub mod service;

use r2e_core::type_list::AllSatisfied;
use r2e_core::EndpointDeps;

pub use guard::{GrpcGuard, GrpcGuardContext, GrpcRoleBasedIdentity, GrpcRolesGuard};
pub use identity::{
    extract_bearer_token, extract_jwt_claims_from_metadata, GrpcIdentityExtractor,
    JwtClaimsValidatorLike,
};
pub use multiplex::MultiplexService;
pub use registry::{GrpcServiceRegistry, RegisteredServices};
pub use server::{GrpcMarker, GrpcServer, GrpcTransport};
pub use service::GrpcService;

// Re-export tonic for use by generated code.
pub use prost;
pub use tonic;

/// Include the proto modules generated by the `r2e-grpc-build` build helper.
///
/// Expands to the aggregator `r2e-grpc-build` writes into `OUT_DIR`
/// (`r2e_protos.rs`): one Rust module per protobuf package (dotted packages
/// nest) plus a `FILE_DESCRIPTOR_SET` constant with the combined encoded
/// descriptor set for gRPC server reflection.
///
/// ```ignore
/// // build.rs: fn main() -> Result<(), Box<dyn std::error::Error>> { r2e_grpc_build::compile() }
/// pub mod proto {
///     r2e::r2e_grpc::include_protos!();
/// }
///
/// use proto::greeter::{HelloReply, HelloRequest};
///
/// #[grpc_routes(proto::greeter::greeter_server::Greeter,
///               descriptor = proto::FILE_DESCRIPTOR_SET)]
/// impl GreeterService { /* … */ }
/// ```
#[macro_export]
macro_rules! include_protos {
    () => {
        include!(concat!(env!("OUT_DIR"), "/r2e_protos.rs"));
    };
}

/// Extension trait for `AppBuilder` to register gRPC services.
///
/// This is the gRPC analog of `register_controller` for HTTP — including the
/// compile-time dependency check: the service's [`EndpointDeps`] (its core's
/// `#[inject]` fields plus every `#[intercept(...)]` spec's deps, emitted by
/// `#[grpc_routes]`) are checked against the application state via
/// `AllSatisfied`, so a missing bean is a compile error at this call site.
///
/// `T` and `DepIdx` are inference-only witnesses (the same pattern as
/// [`RegisterController`](r2e_core::RegisterController)): call sites write
/// `.register_grpc_service::<UserGrpcService>()` and never name them.
///
/// # Example
///
/// ```ignore
/// use r2e_grpc::AppBuilderGrpcExt;
///
/// AppBuilder::new()
///     .plugin(GrpcServer::on_port("0.0.0.0:50051"))
///     .build_state()
///     .await
///     .register_grpc_service::<UserGrpcService>()
///     .register_grpc_service::<OrderGrpcService>()
///     .serve("0.0.0.0:3000")
/// ```
pub trait AppBuilderGrpcExt<T, DepIdx>: Sized
where
    T: Clone + Send + Sync + 'static,
{
    /// Register a gRPC service whose handler is wired into the gRPC server.
    ///
    /// The service is built immediately from the retained bean graph
    /// ([`AppBuilder::bean_context`](r2e_core::AppBuilder::bean_context)).
    ///
    /// # Panics
    ///
    /// Panics if config keys or sections declared on the service (or on any of
    /// its `#[intercept]` decorator specs) fail validation. Use
    /// [`try_register_grpc_service`](Self::try_register_grpc_service) for a
    /// non-panicking alternative — the gRPC peer of
    /// [`try_register_controller`](r2e_core::RegisterController::try_register_controller).
    fn register_grpc_service<S>(self) -> Self
    where
        S: GrpcService + EndpointDeps,
        S::Deps: AllSatisfied<T, DepIdx>;

    /// Register a gRPC service, returning config-validation errors instead of
    /// panicking.
    ///
    /// Behaves exactly like
    /// [`register_grpc_service`](Self::register_grpc_service) on success. On
    /// failure the service's aggregated
    /// [`ConfigValidationError`](r2e_core::config::ConfigValidationError) is
    /// returned and the builder is consumed (startup wiring cannot proceed with
    /// a misconfigured service).
    fn try_register_grpc_service<S>(
        self,
    ) -> Result<Self, r2e_core::config::ConfigValidationError>
    where
        S: GrpcService + EndpointDeps,
        S::Deps: AllSatisfied<T, DepIdx>;
}

impl<T, DepIdx> AppBuilderGrpcExt<T, DepIdx> for r2e_core::AppBuilder<T>
where
    T: Clone + Send + Sync + 'static,
{
    fn register_grpc_service<S>(self) -> Self
    where
        S: GrpcService + EndpointDeps,
        S::Deps: AllSatisfied<T, DepIdx>,
    {
        self.try_register_grpc_service::<S>().unwrap_or_else(|err| {
            panic!(
                "\n=== CONFIGURATION ERRORS (grpc service: {}) ===\n\n{}\n============================\n",
                std::any::type_name::<S>(),
                err
            )
        })
    }

    fn try_register_grpc_service<S>(
        self,
    ) -> Result<Self, r2e_core::config::ConfigValidationError>
    where
        S: GrpcService + EndpointDeps,
        S::Deps: AllSatisfied<T, DepIdx>,
    {
        // Aggregated config validation, before anything is built — the gRPC
        // peer of the `register_controller` banner. Covers the core's own
        // `#[config]` keys and every `#[intercept]` decorator spec's.
        if let Some(config) = self.r2e_config() {
            let errors = S::validate_config(config);
            if !errors.is_empty() {
                return Err(r2e_core::config::ConfigValidationError { errors });
            }
        }

        let registry = self
            .get_plugin_data::<GrpcServiceRegistry>()
            .expect(
                "GrpcServiceRegistry not found. Did you install `.plugin(GrpcServer::...)` before build_state()?",
            )
            .clone();

        registry.add_service(S::service_name(), S::file_descriptor_set(), |routes| {
            S::add_to_routes(routes, self.bean_context())
        });

        tracing::debug!(service = S::service_name(), "Registered gRPC service");

        Ok(self)
    }
}

/// Re-exports for generated code.
#[doc(hidden)]
pub mod __macro_support {
    pub use crate::guard::{GrpcGuard, GrpcGuardContext, GrpcRoleBasedIdentity, GrpcRolesGuard};
    pub use crate::identity::{GrpcIdentityExtractor, JwtClaimsValidatorLike};
    pub use crate::service::GrpcService;
    pub use r2e_core::ContextConstruct;
    pub use r2e_core::Identity;
    pub use tonic;
}

pub mod prelude {
    //! Re-exports of the most commonly used gRPC types.
    pub use crate::guard::{GrpcGuard, GrpcGuardContext, GrpcRoleBasedIdentity};
    pub use crate::server::GrpcServer;
    pub use crate::service::GrpcService;
    pub use crate::AppBuilderGrpcExt;
}
