/// Trait for gRPC services that can be registered with the R2E builder.
///
/// Implement this trait (typically via the `#[grpc_routes]` macro) to wire
/// a tonic service into the R2E application. The service is constructed from
/// the resolved bean graph by type (see
/// [`ContextConstruct`](r2e_core::ContextConstruct)) — once, at registration.
///
/// Services accumulate into a single [`tonic::service::Routes`] collection
/// (one `add_to_routes` call per registered service), which the `GrpcServer`
/// plugin drains once at serve time. This is what lets N services share one
/// gRPC port: `tonic::transport::server::Router` (one per service) cannot be
/// merged, but `Routes` can host any number of services.
///
/// # Example (generated by macro)
///
/// ```ignore
/// impl GrpcService for UserGrpcService {
///     fn service_name() -> &'static str {
///         "mypackage.UserService"
///     }
///
///     fn add_to_routes(
///         routes: tonic::service::Routes,
///         ctx: &Arc<BeanContext>,
///     ) -> tonic::service::Routes {
///         let wrapper = __R2eGrpcUserGrpcService {
///             core: Arc::new(<UserGrpcService as ContextConstruct>::from_context(ctx)),
///             // plus, when any method has `#[intercept(...)]` sites:
///             // __decos: Arc::new(__R2eGrpcDecos_UserGrpcService { ... }),
///             // (interceptor sets prebuilt from `ctx` — never per call)
///         };
///         routes.add_service(proto::user_service_server::UserServiceServer::new(wrapper))
///     }
/// }
/// ```
pub trait GrpcService: 'static {
    /// The proto service name (e.g., "mypackage.UserService").
    fn service_name() -> &'static str;

    /// The encoded `FileDescriptorSet` covering this service's proto file(s),
    /// used by gRPC server reflection ([`GrpcServer::with_reflection`](crate::GrpcServer::with_reflection)).
    ///
    /// `None` (the default) when the service does not carry one. Set it via
    /// the `descriptor` argument of `#[grpc_routes]`, pointing at the bytes
    /// emitted by `tonic_prost_build`'s `file_descriptor_set_path`:
    ///
    /// ```ignore
    /// // build.rs
    /// tonic_prost_build::configure()
    ///     .file_descriptor_set_path(out_dir.join("greeter_descriptor.bin"))
    ///     .compile_protos(&["proto/greeter.proto"], &["proto"])?;
    ///
    /// // proto module
    /// pub const FILE_DESCRIPTOR_SET: &[u8] =
    ///     tonic::include_file_descriptor_set!("greeter_descriptor");
    ///
    /// // service
    /// #[grpc_routes(proto::greeter_server::Greeter, descriptor = proto::FILE_DESCRIPTOR_SET)]
    /// impl GreeterService { ... }
    /// ```
    fn file_descriptor_set() -> Option<&'static [u8]> {
        None
    }

    /// Add this service to the given route collection, constructing it from
    /// the resolved bean graph.
    fn add_to_routes(
        routes: tonic::service::Routes,
        ctx: &std::sync::Arc<r2e_core::beans::BeanContext>,
    ) -> tonic::service::Routes;
}
