use crate::http::response::{IntoHttpResponse, Response};

/// Where a `#[derive(Params)]` field is read from — decides the
/// [`RejectionKind`](crate::error::RejectionKind) of a failed extraction.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ParamLocation {
    /// A route path segment.
    Path,
    /// A query-string key.
    Query,
    /// A request header.
    Header,
}

/// Error type for parameter extraction failures in `#[derive(Params)]`.
#[derive(Debug)]
pub struct ParamError {
    pub location: ParamLocation,
    pub message: String,
}

impl std::fmt::Display for ParamError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.message)
    }
}

impl IntoHttpResponse for ParamError {
    /// Standalone rendering (outside a generated route): the default
    /// [`HttpError`](crate::HttpError) projection of the equivalent
    /// [`Rejection`](crate::Rejection). Generated routes never call this —
    /// they convert into the hub type and project once.
    fn into_http_response(self) -> Response {
        crate::error::Rejection::from(self).into_http_response()
    }
}

crate::http::impl_into_response!(ParamError);

impl From<ParamError> for Response {
    fn from(err: ParamError) -> Self {
        err.into_http_response()
    }
}

/// Parse a query string into key-value pairs.
pub fn parse_query_string(query: Option<&str>) -> Vec<(String, String)> {
    match query {
        Some(q) => form_urlencoded::parse(q.as_bytes())
            .map(|(k, v)| (k.into_owned(), v.into_owned()))
            .collect(),
        None => Vec::new(),
    }
}

// ── ParamsMetadata: OpenAPI parameter metadata for #[derive(Params)] ──

use crate::di::meta::ParamInfo;

/// Trait for types that expose parameter metadata for OpenAPI spec generation.
/// Auto-implemented by `#[derive(Params)]`.
pub trait ParamsMetadata {
    fn param_infos() -> Vec<ParamInfo>;
}

// ── Autoref specialization support ──
//
// Allows generated code to call `param_infos()` on any handler parameter type:
// - Types implementing ParamsMetadata → returns real metadata (inherent method)
// - Other types → returns empty vec (fallback via autoref to __NoParamsMeta)

#[doc(hidden)]
pub struct __ParamMetaProbe<T>(pub core::marker::PhantomData<T>);

impl<T: ParamsMetadata> __ParamMetaProbe<T> {
    pub fn param_infos(&self) -> Vec<ParamInfo> {
        T::param_infos()
    }
}

#[doc(hidden)]
pub trait __NoParamsMeta {
    fn param_infos(&self) -> Vec<ParamInfo> {
        Vec::new()
    }
}

impl<T> __NoParamsMeta for &__ParamMetaProbe<T> {}

// ── PrefixedExtract: core extraction trait for nested Params support ──

/// Trait for Params types that support prefixed extraction.
/// Generated by `#[derive(Params)]`. `FromRequestParts` delegates to this with empty prefix.
pub trait PrefixedExtract<S: Send + Sync>: Sized {
    fn extract_prefixed(
        parts: &mut crate::http::header::Parts,
        state: &S,
        prefix: &str,
    ) -> impl std::future::Future<Output = Result<Self, ParamError>> + Send;
}

/// Build a prefixed query key. Returns borrowed `key` when prefix is empty (no allocation).
pub fn prefixed_key<'a>(prefix: &str, key: &'a str) -> std::borrow::Cow<'a, str> {
    if prefix.is_empty() {
        std::borrow::Cow::Borrowed(key)
    } else {
        std::borrow::Cow::Owned(format!("{prefix}.{key}"))
    }
}
