//! OpenFGA guard for fine-grained authorization checks.

use crate::error::OpenFgaError;
use crate::registry::OpenFgaRegistry;
use r2e_core::beans::BeanContext;
use r2e_core::guards::{Guard, GuardContext, Identity};
use r2e_core::http::response::IntoResponse;
use r2e_core::type_list::{TCons, TNil};
use r2e_core::{DecoratorSpec, PathParam};

/// A source for a route path-parameter name accepted by
/// [`FgaObjectBuilder::from_path`].
///
/// Two forms are supported:
/// - a raw `&'static str` (`from_path("doc_id")`) — no compile-time check;
/// - a [`PathParam`] descriptor from the `#[routes]`-generated `path` module
///   (`from_path(path::doc_id)`) — the descriptor only exists when the route
///   actually declares a `{doc_id}` placeholder, so a typo or a param that the
///   route does not expose is a **compile error** at the guard site.
///
/// Prefer the `path::<name>` form: it keeps the guard and the route path in
/// sync at build time.
pub trait PathParamName {
    /// The path-parameter name to resolve the object ID from.
    fn param_name(self) -> &'static str;
}

impl PathParamName for &'static str {
    fn param_name(self) -> &'static str {
        self
    }
}

impl<T> PathParamName for PathParam<T> {
    fn param_name(self) -> &'static str {
        self.name
    }
}

/// How to resolve the object ID for authorization checks.
#[derive(Debug, Clone)]
pub enum ObjectResolver {
    /// Extract from a path parameter (e.g., `{doc_id}` in route).
    PathParam(&'static str),
    /// Extract from a query string parameter.
    QueryParam(&'static str),
    /// Extract from a header.
    Header(&'static str),
    /// Use a fixed object ID.
    Fixed(&'static str),
}

/// FGA authorization check config.
///
/// A plain config value produced by the `FgaCheck::relation(...).on(...)`
/// builder chain and used with `#[guard(...)]`. Its [`DecoratorSpec`] impl
/// pulls the [`OpenFgaRegistry`] bean from the graph at controller
/// registration and moves it into the built [`FgaGuard`]. The check itself
/// (object resolution) is pure and needs no bean, so it lives here.
///
/// # Examples
///
/// ```ignore
/// use r2e_openfga::FgaCheck;
///
/// // Check using query parameter
/// #[guard(FgaCheck::relation("viewer").on("document").from_query("doc_id"))]
///
/// // Check using header
/// #[guard(FgaCheck::relation("editor").on("document").from_header("X-Document-Id"))]
///
/// // Check using fixed object
/// #[guard(FgaCheck::relation("member").on("organization").fixed("org:acme"))]
/// ```
pub struct FgaCheck {
    pub relation: &'static str,
    pub object_type: &'static str,
    pub resolver: ObjectResolver,
}

impl FgaCheck {
    /// Start building a check for a **typed** relation generated by
    /// `model!` — the one argument carries both the relation and its object
    /// type, checked against the `.fga` model at compile time.
    ///
    /// ```ignore
    /// r2e_openfga::model!(pub mod authz = "fga/model.fga");
    ///
    /// #[guard(FgaCheck::has(authz::document::viewer).from_path(path::doc_id))]
    /// ```
    ///
    /// Prefer this over [`relation`](Self::relation)`(...).on(...)`: a typo'd
    /// relation is an unresolved name at the guard site instead of a
    /// permanent 403 in production.
    pub fn has<T, R>(rel: crate::typed::FgaRel<T, R>) -> FgaObjectBuilder
    where
        T: crate::typed::FgaType,
    {
        FgaObjectBuilder {
            relation: rel.name(),
            object_type: T::NAME,
        }
    }

    /// Start building a check for the given relation.
    ///
    /// This is the **unchecked** escape hatch for dynamic models: nothing
    /// verifies the relation or object type exist. With a checked-in `.fga`
    /// model, prefer [`has`](Self::has).
    pub fn relation(relation: &'static str) -> FgaCheckBuilder {
        FgaCheckBuilder { relation }
    }

    /// Resolve the object ID from the request context.
    ///
    /// For dynamic resolvers (`PathParam`, `QueryParam`, `Header`), the resolved
    /// value is treated as a raw ID and formatted as `"type:id"`. Colons are
    /// rejected in the raw ID to prevent object type injection (e.g. an attacker
    /// supplying `"secret:admin"` to bypass the declared object type).
    ///
    /// For `Fixed`, the value is used as-is (it is developer-controlled).
    pub fn resolve_object<I: Identity>(
        &self,
        ctx: &GuardContext<'_, I>,
    ) -> Result<String, OpenFgaError> {
        match &self.resolver {
            ObjectResolver::Fixed(object) => Ok(object.to_string()),
            resolver => {
                let raw_id = match resolver {
                    ObjectResolver::PathParam(param) => ctx
                        .path_param(param)
                        .map(|s| s.to_string())
                        .ok_or_else(|| {
                            OpenFgaError::ObjectResolutionFailed(format!(
                                "path param '{}' not found",
                                param
                            ))
                        })?,
                    ObjectResolver::QueryParam(param) => ctx
                        .query_string()
                        .and_then(|qs| {
                            url::form_urlencoded::parse(qs.as_bytes())
                                .find(|(k, _)| k == *param)
                                .map(|(_, v)| v.into_owned())
                        })
                        .ok_or_else(|| {
                            OpenFgaError::ObjectResolutionFailed(format!(
                                "query param '{}' not found",
                                param
                            ))
                        })?,
                    ObjectResolver::Header(header) => ctx
                        .headers
                        .get(*header)
                        .and_then(|v| v.to_str().ok())
                        .map(|s| s.to_string())
                        .ok_or_else(|| {
                            OpenFgaError::ObjectResolutionFailed(format!(
                                "header '{}' not found",
                                header
                            ))
                        })?,
                    ObjectResolver::Fixed(_) => unreachable!(),
                };

                // Reject FGA metacharacters in dynamic IDs: ':' would inject
                // an object type ("secret:admin" bypassing the declared one),
                // '#' a userset reference, '*' a wildcard.
                if raw_id.contains([':', '#', '*']) {
                    return Err(OpenFgaError::ObjectResolutionFailed(format!(
                        "object ID must not contain ':', '#', or '*' (got '{}')",
                        raw_id
                    )));
                }

                Ok(format!("{}:{}", self.object_type, raw_id))
            }
        }
    }
}

impl DecoratorSpec for FgaCheck {
    type Product = FgaGuard;
    type Deps = TCons<OpenFgaRegistry, TNil>;

    // The check is `user:{identity.sub()}` — with no identity it can only ever
    // return 401. Declaring the requirement makes `#[routes]` reject an
    // identity-less placement at compile time (see the const-assert emitted per
    // guard site); the runtime `None` → 401 in `FgaGuard::check` stays as the
    // backstop for `Option<..>` identities.
    const REQUIRES_IDENTITY: bool = true;

    fn build(self, ctx: &BeanContext) -> FgaGuard {
        FgaGuard {
            registry: ctx.get::<OpenFgaRegistry>(),
            check: self,
        }
    }
}

/// Builder step: relation has been set, object type needed.
pub struct FgaCheckBuilder {
    relation: &'static str,
}

impl FgaCheckBuilder {
    /// Set the object type. You must then specify how to resolve the object ID.
    pub fn on(self, object_type: &'static str) -> FgaObjectBuilder {
        FgaObjectBuilder {
            relation: self.relation,
            object_type,
        }
    }
}

/// Builder step: object type has been set, resolution method needed.
pub struct FgaObjectBuilder {
    relation: &'static str,
    object_type: &'static str,
}

impl FgaObjectBuilder {
    /// Extract object ID from a path parameter.
    ///
    /// Accepts either a raw `&'static str` or a `path::<name>` descriptor
    /// generated by `#[routes]` (see [`PathParamName`]). The descriptor form is
    /// compile-checked against the route's `{name}` placeholders.
    ///
    /// # Example
    /// ```ignore
    /// // GET /api/documents/{doc_id}
    /// #[guard(FgaCheck::relation("viewer").on("document").from_path(path::doc_id))]
    /// // or, unchecked:
    /// #[guard(FgaCheck::relation("viewer").on("document").from_path("doc_id"))]
    /// ```
    pub fn from_path(self, param: impl PathParamName) -> FgaCheck {
        FgaCheck {
            relation: self.relation,
            object_type: self.object_type,
            resolver: ObjectResolver::PathParam(param.param_name()),
        }
    }

    /// Extract object ID from a query string parameter.
    ///
    /// # Example
    /// ```ignore
    /// // GET /api/documents?doc_id=123
    /// #[guard(FgaCheck::relation("viewer").on("document").from_query("doc_id"))]
    /// ```
    pub fn from_query(self, param: &'static str) -> FgaCheck {
        FgaCheck {
            relation: self.relation,
            object_type: self.object_type,
            resolver: ObjectResolver::QueryParam(param),
        }
    }

    /// Extract object ID from a request header.
    ///
    /// # Example
    /// ```ignore
    /// // Header: X-Document-Id: 123
    /// #[guard(FgaCheck::relation("viewer").on("document").from_header("X-Document-Id"))]
    /// ```
    pub fn from_header(self, header: &'static str) -> FgaCheck {
        FgaCheck {
            relation: self.relation,
            object_type: self.object_type,
            resolver: ObjectResolver::Header(header),
        }
    }

    /// Use a fixed object ID.
    ///
    /// # Example
    /// ```ignore
    /// #[guard(FgaCheck::relation("admin").on("system").fixed("system:global"))]
    /// ```
    pub fn fixed(self, object: &'static str) -> FgaCheck {
        FgaCheck {
            relation: self.relation,
            object_type: self.object_type,
            resolver: ObjectResolver::Fixed(object),
        }
    }
}

/// OpenFGA authorization guard.
///
/// Checks if the current user has the specified relation to an object.
/// The object ID is resolved from the request using the configured resolver.
///
/// Holds the [`OpenFgaRegistry`] as a field (resolved once at controller
/// registration via [`FgaCheck`]'s [`DecoratorSpec`] impl) — there is no state
/// lookup at request time.
pub struct FgaGuard {
    pub registry: OpenFgaRegistry,
    pub check: FgaCheck,
}

impl<I: Identity> Guard<I> for FgaGuard {
    fn check(
        &self,
        ctx: &GuardContext<'_, I>,
    ) -> impl std::future::Future<Output = Result<(), r2e_core::http::Response>> + Send {
        let registry = &self.registry;
        let relation = self.check.relation;
        let object_result = self.check.resolve_object(ctx);

        // Get user ID from identity
        let sub = ctx.identity.map(|i| i.sub().to_string());

        async move {
            let sub = sub.ok_or_else(|| {
                (
                    r2e_core::http::StatusCode::UNAUTHORIZED,
                    r2e_core::http::Json(serde_json::json!({
                        "error": "Authentication required for authorization check"
                    })),
                )
                    .into_response()
            })?;

            // Same injection guard as the object side: `sub` is normally
            // IdP-issued, but if a deployment maps a caller-influenced claim
            // into it, `*` would collapse onto public-wildcard grants, `:`
            // would cross types, and `#` would form a userset reference.
            // Fail closed rather than trust the claim shape.
            if sub.contains([':', '#', '*']) {
                tracing::warn!(
                    sub = %sub,
                    "rejecting FGA check: identity subject contains a reserved character (':', '#', '*')"
                );
                return Err((
                    r2e_core::http::StatusCode::FORBIDDEN,
                    r2e_core::http::Json(serde_json::json!({
                        "error": "Access denied"
                    })),
                )
                    .into_response());
            }
            let user = format!("user:{}", sub);

            let object = object_result.map_err(|e| {
                tracing::warn!(error = %e, "failed to resolve object for FGA check");
                (
                    r2e_core::http::StatusCode::BAD_REQUEST,
                    r2e_core::http::Json(serde_json::json!({
                        "error": format!("Failed to resolve object: {}", e)
                    })),
                )
                    .into_response()
            })?;

            tracing::debug!(
                user = %user,
                relation = %relation,
                object = %object,
                "checking authorization"
            );

            match registry.check(&user, relation, &object).await {
                Ok(true) => Ok(()),
                Ok(false) => {
                    tracing::debug!(
                        user = %user,
                        relation = %relation,
                        object = %object,
                        "authorization denied"
                    );
                    Err((
                        r2e_core::http::StatusCode::FORBIDDEN,
                        r2e_core::http::Json(serde_json::json!({
                            "error": "Access denied"
                        })),
                    )
                        .into_response())
                }
                Err(e) => {
                    tracing::error!(
                        error = %e,
                        user = %user,
                        relation = %relation,
                        object = %object,
                        "authorization check failed"
                    );
                    Err((
                        r2e_core::http::StatusCode::INTERNAL_SERVER_ERROR,
                        r2e_core::http::Json(serde_json::json!({
                            "error": "Authorization check failed"
                        })),
                    )
                        .into_response())
                }
            }
        }
    }
}
