//! Typed markers for schema-first authorization.
//!
//! These types are the runtime side of the `model!` macro: the generated
//! `authz::…` module produces [`FgaType`] markers, [`FgaObject`] constructors
//! and [`FgaRel`] relation consts, so relations and object types used in code
//! are compile-checked against the checked-in `.fga` model. A typo'd relation
//! is an unresolved name, not a silent 403.
//!
//! ```ignore
//! r2e_openfga::model!(pub mod authz = "fga/model.fga");
//!
//! #[guard(FgaCheck::has(authz::document::viewer).from_path(path::doc_id))]
//! ```
//!
//! [`DirectlyAssignable`] encodes the model's `directly_related_user_types`:
//! the typed write API (Phase 2 `FgaClient`) bounds grants on it, so granting
//! a subject type the model does not allow is a compile error too.

use std::fmt;
use std::marker::PhantomData;

/// An object type declared in the `.fga` model. Implemented by the `Ty`
/// markers generated by `model!` (`authz::document::Ty`).
pub trait FgaType {
    /// The type name as written in the model (`document`).
    const NAME: &'static str;
}

/// The error returned by [`FgaObject::try_new`] when the raw id contains an
/// FGA metacharacter: `:` would allow object-type injection
/// (e.g. `secret:admin`), `#` a userset reference, `*` a wildcard.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InvalidObjectId(pub String);

impl fmt::Display for InvalidObjectId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "object ID must not contain ':', '#', or '*' (got '{}')",
            self.0
        )
    }
}

impl std::error::Error for InvalidObjectId {}

/// A typed FGA object reference: `document:readme`.
///
/// Construct via the generated `authz::<type>::id(...)` / `try_id(...)` —
/// the type half comes from the model, the id half from your data.
pub struct FgaObject<T: FgaType> {
    rendered: String,
    _ty: PhantomData<T>,
}

// Manual impls: marker types carry no data, so no bounds on `T`.
impl<T: FgaType> fmt::Debug for FgaObject<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_tuple("FgaObject").field(&self.rendered).finish()
    }
}
impl<T: FgaType> Clone for FgaObject<T> {
    fn clone(&self) -> Self {
        FgaObject {
            rendered: self.rendered.clone(),
            _ty: PhantomData,
        }
    }
}
impl<T: FgaType> PartialEq for FgaObject<T> {
    fn eq(&self, other: &Self) -> bool {
        self.rendered == other.rendered
    }
}
impl<T: FgaType> Eq for FgaObject<T> {}
impl<T: FgaType> std::hash::Hash for FgaObject<T> {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.rendered.hash(state);
    }
}

impl<T: FgaType> FgaObject<T> {
    /// Build `T::NAME:id`, rejecting ids containing `:`, `#`, or `*` (the
    /// same injection guard as the request-time object resolvers).
    pub fn try_new(id: impl AsRef<str>) -> Result<Self, InvalidObjectId> {
        let id = id.as_ref();
        if id.contains([':', '#', '*']) {
            return Err(InvalidObjectId(id.to_string()));
        }
        Ok(FgaObject {
            rendered: format!("{}:{}", T::NAME, id),
            _ty: PhantomData,
        })
    }

    /// Like [`try_new`](Self::try_new) but panics on an invalid id. Use with
    /// developer-controlled ids (database keys); prefer `try_new` for
    /// request-supplied input.
    pub fn new(id: impl AsRef<str>) -> Self {
        Self::try_new(id).unwrap_or_else(|e| panic!("{}: {}", T::NAME, e))
    }

    /// The full `type:id` string.
    pub fn as_str(&self) -> &str {
        &self.rendered
    }

    /// The id half (after the `:`).
    pub fn id(&self) -> &str {
        &self.rendered[T::NAME.len() + 1..]
    }
}

impl<T: FgaType> fmt::Display for FgaObject<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.rendered)
    }
}

/// A typed relation on object type `T`, generated by `model!` as a lowercase
/// const (`authz::document::viewer: FgaRel<Ty, Viewer>`). Carries the
/// relation name and, in `R`, a per-relation marker used for
/// [`DirectlyAssignable`] bounds.
pub struct FgaRel<T: FgaType, R> {
    name: &'static str,
    _m: PhantomData<(T, R)>,
}

impl<T: FgaType, R> FgaRel<T, R> {
    /// Used by generated code — not intended to be called directly.
    #[doc(hidden)]
    pub const fn new(name: &'static str) -> Self {
        FgaRel {
            name,
            _m: PhantomData,
        }
    }

    /// The relation name as written in the model.
    pub fn name(self) -> &'static str {
        self.name
    }

    /// The object type name this relation is defined on.
    pub fn object_type(self) -> &'static str {
        T::NAME
    }

    /// Reference the userset `object#relation` (e.g. `team:eng#member`) for
    /// use as a grant subject.
    pub fn of(self, object: FgaObject<T>) -> FgaUserset<T, R> {
        FgaUserset {
            rendered: format!("{}#{}", object.as_str(), self.name),
            _m: PhantomData,
        }
    }
}

impl<T: FgaType, R> Clone for FgaRel<T, R> {
    fn clone(&self) -> Self {
        *self
    }
}
impl<T: FgaType, R> Copy for FgaRel<T, R> {}

/// A typed userset subject: `team:eng#member`.
pub struct FgaUserset<T: FgaType, R> {
    rendered: String,
    _m: PhantomData<(T, R)>,
}

impl<T: FgaType, R> fmt::Debug for FgaUserset<T, R> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_tuple("FgaUserset").field(&self.rendered).finish()
    }
}
impl<T: FgaType, R> Clone for FgaUserset<T, R> {
    fn clone(&self) -> Self {
        FgaUserset {
            rendered: self.rendered.clone(),
            _m: PhantomData,
        }
    }
}
impl<T: FgaType, R> PartialEq for FgaUserset<T, R> {
    fn eq(&self, other: &Self) -> bool {
        self.rendered == other.rendered
    }
}
impl<T: FgaType, R> Eq for FgaUserset<T, R> {}
impl<T: FgaType, R> std::hash::Hash for FgaUserset<T, R> {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.rendered.hash(state);
    }
}

impl<T: FgaType, R> FgaUserset<T, R> {
    /// The full `type:id#relation` string.
    pub fn as_str(&self) -> &str {
        &self.rendered
    }
}

impl<T: FgaType, R> fmt::Display for FgaUserset<T, R> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.rendered)
    }
}

/// The public wildcard subject: `user:*`. Assignable only where the model
/// declares `[user:*]`.
pub struct FgaWildcard<T: FgaType>(PhantomData<T>);

impl<T: FgaType> fmt::Debug for FgaWildcard<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "FgaWildcard(\"{}:*\")", T::NAME)
    }
}
impl<T: FgaType> Clone for FgaWildcard<T> {
    fn clone(&self) -> Self {
        *self
    }
}
impl<T: FgaType> Copy for FgaWildcard<T> {}
impl<T: FgaType> PartialEq for FgaWildcard<T> {
    fn eq(&self, _: &Self) -> bool {
        true
    }
}
impl<T: FgaType> Eq for FgaWildcard<T> {}

impl<T: FgaType> FgaWildcard<T> {
    pub const fn new() -> Self {
        FgaWildcard(PhantomData)
    }
}

impl<T: FgaType> Default for FgaWildcard<T> {
    fn default() -> Self {
        Self::new()
    }
}

impl<T: FgaType> fmt::Display for FgaWildcard<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}:*", T::NAME)
    }
}

/// Marker pairing a wildcard subject with its type in
/// [`DirectlyAssignable`] bounds (`[user:*]` ⇒
/// `DirectlyAssignable<WildcardOf<user::Ty>>`).
pub struct WildcardOf<T: FgaType>(PhantomData<T>);

/// Anything that can be the subject of a relationship tuple: a typed object
/// (`user:alice`), a userset (`team:eng#member`), or a wildcard (`user:*`).
pub trait FgaSubject {
    /// The marker checked against [`DirectlyAssignable`]: the type marker
    /// itself for objects, `(Ty, RelMarker)` for usersets,
    /// [`WildcardOf<Ty>`] for wildcards.
    type Marker;

    /// The wire form (`user:alice`, `team:eng#member`, `user:*`).
    fn subject_str(&self) -> &str;
}

impl<T: FgaType> FgaSubject for FgaObject<T> {
    type Marker = T;

    fn subject_str(&self) -> &str {
        self.as_str()
    }
}

impl<T: FgaType, R> FgaSubject for FgaUserset<T, R> {
    type Marker = (T, R);

    fn subject_str(&self) -> &str {
        self.as_str()
    }
}

/// `FgaWildcard` renders lazily, so it keeps an owned copy per call site.
impl<T: FgaType> FgaSubject for FgaWildcard<T> {
    type Marker = WildcardOf<T>;

    fn subject_str(&self) -> &str {
        // `T::NAME:*` is 'static-derivable but not const-concatenable on
        // stable; leak once per type via OnceLock.
        static_wildcard::<T>()
    }
}

fn static_wildcard<T: FgaType>() -> &'static str {
    use std::collections::HashMap;
    use std::sync::{Mutex, OnceLock};
    static CACHE: OnceLock<Mutex<HashMap<&'static str, &'static str>>> = OnceLock::new();
    let cache = CACHE.get_or_init(|| Mutex::new(HashMap::new()));
    let mut map = cache.lock().expect("wildcard cache poisoned");
    map.entry(T::NAME)
        .or_insert_with(|| Box::leak(format!("{}:*", T::NAME).into_boxed_str()))
}

/// Implemented (by `model!`-generated code) on a relation marker for every
/// subject marker in the relation's `directly_related_user_types`. The typed
/// write API bounds `grant`/`revoke` on it: assigning a subject type the
/// model does not allow fails to compile.
pub trait DirectlyAssignable<SubjectMarker> {}
