/// Construct a controller from the application state alone (no HTTP context).
///
/// Auto-generated by `#[derive(Controller)]` for controllers that do **not**
/// have `#[inject(identity)]` fields. Used internally by consumer and
/// scheduled-task code paths.
#[diagnostic::on_unimplemented(
    message = "`{Self}` cannot be constructed from state alone",
    note = "controllers with #[inject(identity)] fields require an HTTP context"
)]
pub trait StatefulConstruct<S> {
    fn from_state(state: &S) -> Self;
}

pub trait Controller<T: Clone + Send + Sync + 'static> {
    fn routes() -> crate::http::Router<T>;

    /// Apply pre-authentication guard layers to specific routes.
    ///
    /// Called by `register_controller()` with the application state after building
    /// the base routes. The default implementation returns the router unchanged.
    ///
    /// This is generated by the `#[routes]` macro when `#[rate_limited]` guards
    /// with global or IP keys are present, or when `#[pre_guard]` is used.
    fn apply_pre_auth_guards(router: crate::http::Router<T>, _state: &T) -> crate::http::Router<T> {
        router
    }

    /// Return metadata about all routes registered by this controller.
    /// Used for OpenAPI spec generation. Default returns an empty list.
    fn route_metadata() -> Vec<crate::openapi::RouteInfo> {
        Vec::new()
    }

    /// Register event consumers for this controller.
    ///
    /// Called during `serve()` with the application state, before startup hooks.
    /// The default implementation does nothing.
    fn register_consumers(
        _state: T,
    ) -> std::pin::Pin<Box<dyn std::future::Future<Output = ()> + Send>> {
        Box::pin(async {})
    }

    /// Return scheduled task definitions declared via `#[scheduled]`.
    ///
    /// Returns type-erased task definitions. Each task is a
    /// `Box<Box<dyn ScheduledTask>>` wrapped in `Box<dyn Any + Send>`.
    /// This double-boxing allows the scheduler to downcast and start tasks
    /// without knowing the concrete state type.
    ///
    /// The `state` parameter is cloned into each task, so tasks have all
    /// the state they need to run independently.
    ///
    /// Called by `register_controller()` to collect tasks automatically.
    /// The default implementation returns an empty list.
    fn scheduled_tasks_boxed(state: &T) -> Vec<Box<dyn std::any::Any + Send>> {
        let _ = state;
        Vec::new()
    }
}
