/// Construct a controller from the application state alone (no HTTP context).
///
/// Auto-generated by `#[controller(...)]`. Request-scoped fields are held by
/// the generated request facade, so the physical controller core is always
/// constructible from application state alone.
#[diagnostic::on_unimplemented(
    message = "`{Self}` cannot be constructed from state alone",
    note = "controller cores must use #[controller(state = ...)] or implement StatefulConstruct manually"
)]
pub trait StatefulConstruct<S> {
    fn from_state(state: &S) -> Self;
}

pub trait Controller<T: Clone + Send + Sync + 'static>:
    StatefulConstruct<T> + Send + Sync + 'static
{
    /// Build this controller's routes from the resolved application state.
    ///
    /// State-aware construction is the only registration path. Generated
    /// controllers receive the shared core built by `register_controller()` and
    /// install pre-authentication guards before state finalization.
    fn routes(state: &T, core: std::sync::Arc<Self>) -> crate::http::Router<T>;

    /// Push metadata about this controller's routes into the registry.
    ///
    /// Called by `register_controller()`. The default implementation is a no-op.
    fn register_meta(_registry: &mut crate::meta::MetaRegistry) {}

    /// Register event consumers for this controller.
    ///
    /// Called during `serve()` with the application state and the shared core,
    /// before startup hooks. The default implementation does nothing.
    fn register_consumers(
        _state: T,
        _core: std::sync::Arc<Self>,
    ) -> std::pin::Pin<Box<dyn std::future::Future<Output = ()> + Send>> {
        Box::pin(async {})
    }

    /// Return scheduled task definitions declared via `#[scheduled]`.
    ///
    /// Returns type-erased task definitions. Each task is a
    /// `Box<Box<dyn ScheduledTask>>` wrapped in `Box<dyn Any + Send>`.
    /// This double-boxing allows the scheduler to downcast and start tasks
    /// without knowing the concrete state type.
    ///
    /// The `state` parameter is cloned into each task definition. Every task
    /// execution receives the same shared controller core.
    ///
    /// Called by `register_controller()` to collect tasks automatically.
    /// The default implementation returns an empty list.
    fn scheduled_tasks_boxed(
        state: &T,
        _core: std::sync::Arc<Self>,
    ) -> Vec<Box<dyn std::any::Any + Send>> {
        let _ = state;
        Vec::new()
    }

    /// Validate all config requirements declared on the controller.
    ///
    /// This covers both `#[config("key")]` individual fields and
    /// `#[config_section]` typed sections. Called automatically by
    /// `register_controller()` when a `R2eConfig` is available.
    /// The default implementation returns an empty list.
    fn validate_config(_config: &crate::config::R2eConfig) -> Vec<crate::config::MissingKeyError> {
        Vec::new()
    }
}
