/// Construct a controller core (or service) from the resolved bean graph,
/// **by type**.
///
/// Auto-generated by `#[controller(...)]` for state-generic controllers: each
/// `#[inject]` field is pulled with `ctx.get::<FieldType>()` and `#[config]`
/// fields are resolved from the `R2eConfig` bean. Construction happens once at
/// registration time; request-scoped fields live on the generated request
/// façade, never on the core.
#[diagnostic::on_unimplemented(
    message = "`{Self}` cannot be constructed from the bean context",
    note = "annotate the struct with #[controller(...)] or implement ContextConstruct manually"
)]
pub trait ContextConstruct {
    /// Type-level list ([`TCons`](crate::type_list::TCons) /
    /// [`TNil`](crate::type_list::TNil)) of the bean types this controller
    /// injects (including `R2eConfig` when `#[config]` fields are present).
    ///
    /// Checked against the application state at `register_controller()` via
    /// [`AllSatisfied`](crate::type_list::AllSatisfied), so a missing bean is
    /// a compile error at the registration call site.
    type Deps;

    /// Pull every app-scoped field from the resolved context.
    fn from_context(ctx: &crate::beans::BeanContext) -> Self;
}

/// State-independent carrier of a controller's **full** dependency list:
/// [`ContextConstruct::Deps`] extended with every guard/interceptor site's
/// [`DecoratorSpec::Deps`](crate::decorator::DecoratorSpec::Deps).
///
/// Emitted by `#[routes]` alongside the [`Controller`] impl. The list is the
/// same one `Controller::Deps` resolves to, but nameable without a state type
/// or extraction witnesses — which is what lets `register_module` check
/// controller dependencies (including decorator deps) against the module scope
/// in the NoState phase, before the state type exists.
#[doc(hidden)]
#[diagnostic::on_unimplemented(
    message = "`{Self}` has no `#[routes]` impl",
    note = "a controller placed in a module's `Controllers` needs a `#[routes]` block \
            (or, for a hand-written controller, a manual `ControllerDeps` impl)"
)]
pub trait ControllerDeps {
    /// Type-level list of every bean this controller's core and decorators read.
    type Deps;
}

/// A registrable HTTP controller.
///
/// `T` is the application state type. `W` is an opaque witness carrier for
/// state-generic controllers: the generated impl parks the inferred extraction
/// markers (see [`FromRequestPartsVia`](crate::extract::FromRequestPartsVia))
/// there. Named-state controllers use the default `W = ()`. User code never
/// names `W` — registration infers it.
pub trait Controller<T: Clone + Send + Sync + 'static, W = ()>: Send + Sync + 'static {
    /// Type-level list of the bean types this controller's core injects.
    ///
    /// Checked against the state at `register_controller()`; the named-state
    /// path uses `TNil` (field presence is checked structurally there).
    type Deps;

    /// Build the controller core at registration time.
    ///
    /// State-generic controllers construct from the resolved bean graph
    /// (`ctx`); named-state controllers construct from the typed state.
    fn construct(state: &T, ctx: &crate::beans::BeanContext) -> Self;

    /// Build this controller's routes from the resolved application state.
    ///
    /// Generated controllers receive the shared core built by
    /// `register_controller()` and install pre-authentication guards before
    /// state finalization. `ctx` is the resolved bean graph: route decorators
    /// (guards/interceptors, see [`DecoratorSpec`](crate::decorator::DecoratorSpec))
    /// are built from it here, once, and moved into the handler closures.
    fn routes(
        state: &T,
        core: std::sync::Arc<Self>,
        ctx: &crate::beans::BeanContext,
    ) -> crate::http::Router<T>;

    /// Push metadata about this controller's routes into the registry.
    ///
    /// Called by `register_controller()`. The default implementation is a no-op.
    fn register_meta(_registry: &mut crate::meta::MetaRegistry) {}

    /// Register event consumers for this controller.
    ///
    /// Called during `serve()` with the application state and the shared core,
    /// before startup hooks. The default implementation does nothing.
    fn register_consumers(
        _state: T,
        _core: std::sync::Arc<Self>,
    ) -> std::pin::Pin<Box<dyn std::future::Future<Output = ()> + Send>> {
        Box::pin(async {})
    }

    /// Return scheduled task definitions declared via `#[scheduled]`.
    ///
    /// Returns type-erased task definitions. Each task is a
    /// `Box<Box<dyn ScheduledTask>>` wrapped in `Box<dyn Any + Send>`.
    /// This double-boxing allows the scheduler to downcast and start tasks
    /// without knowing the concrete state type.
    ///
    /// The `state` parameter is cloned into each task definition. Every task
    /// execution receives the same shared controller core.
    ///
    /// Called by `register_controller()` to collect tasks automatically.
    /// The default implementation returns an empty list.
    fn scheduled_tasks_boxed(
        state: &T,
        _core: std::sync::Arc<Self>,
    ) -> Vec<Box<dyn std::any::Any + Send>> {
        let _ = state;
        Vec::new()
    }

    /// Validate all config requirements declared on the controller.
    ///
    /// This covers both `#[config("key")]` individual fields and
    /// `#[config_section]` typed sections. Called automatically by
    /// `register_controller()` when a `R2eConfig` is available.
    /// The default implementation returns an empty list.
    fn validate_config(_config: &crate::config::R2eConfig) -> Vec<crate::config::MissingKeyError> {
        Vec::new()
    }
}
