/// Construct a controller core (or service) from the resolved bean graph,
/// **by type**.
///
/// Auto-generated by `#[controller(...)]` for state-generic controllers: each
/// `#[inject]` field is pulled with `ctx.get::<FieldType>()` and `#[config]`
/// fields are resolved from the `R2eConfig` bean. Construction happens once at
/// registration time; request-scoped fields live on the generated request
/// façade, never on the core.
#[diagnostic::on_unimplemented(
    message = "`{Self}` cannot be constructed from the bean context",
    note = "annotate the struct with #[controller(...)] or implement ContextConstruct manually"
)]
pub trait ContextConstruct {
    /// Type-level list ([`TCons`](crate::type_list::TCons) /
    /// [`TNil`](crate::type_list::TNil)) of the bean types this controller
    /// injects (including `R2eConfig` when `#[config]` fields are present).
    ///
    /// Checked against the application state at `register_controller()` via
    /// [`AllSatisfied`](crate::type_list::AllSatisfied), so a missing bean is
    /// a compile error at the registration call site.
    type Deps;

    /// Pull every app-scoped field from the resolved context.
    fn from_context(ctx: &crate::beans::BeanContext) -> Self;
}

/// State-independent carrier of an endpoint's **full** dependency list:
/// [`ContextConstruct::Deps`] extended with every guard/interceptor site's
/// [`DecoratorSpec::Deps`](crate::decorator::DecoratorSpec::Deps).
///
/// This is the transport-neutral registration contract: anything that is
/// built from the bean graph and carries decorator sites — an HTTP
/// controller, a gRPC service, a future wire adapter — emits this carrier,
/// and its registration path checks `Deps` against the application state
/// (`AllSatisfied`) or the module scope (`ModuleDepsSatisfied`). Emitted by
/// `#[routes]` alongside the [`Controller`] impl and by `#[grpc_routes]`
/// alongside the `GrpcService` impl. The list is nameable without a state
/// type or extraction witnesses — which is what lets `register_module` check
/// controller dependencies (including decorator deps) against the module
/// scope in the NoState phase, before the state type exists.
///
/// One type carries **one** endpoint dep list: a struct cannot host both a
/// `#[routes]` and a `#[grpc_routes]` block (the two impls would collide).
/// Expose the same logic over two transports by delegating to a shared bean
/// from two endpoint types.
#[doc(hidden)]
#[diagnostic::on_unimplemented(
    message = "`{Self}` has no `#[routes]` or `#[grpc_routes]` impl",
    note = "an endpoint type needs a `#[routes]` / `#[grpc_routes]` block \
            (or, for a hand-written endpoint, a manual `EndpointDeps` impl)"
)]
pub trait EndpointDeps {
    /// Type-level list of every bean this endpoint's core and decorators read.
    type Deps;
}

/// A registrable HTTP controller.
///
/// `T` is the application state type. `W` is an opaque witness carrier for
/// state-generic controllers: the generated impl parks the inferred extraction
/// markers (see [`FromRequestPartsVia`](crate::extract::FromRequestPartsVia))
/// there. Named-state controllers use the default `W = ()`. User code never
/// names `W` — registration infers it.
pub trait Controller<T: Clone + Send + Sync + 'static, W = ()>: Send + Sync + 'static {
    /// Type-level list of the bean types this controller's core injects.
    ///
    /// Checked against the state at `register_controller()`; the named-state
    /// path uses `TNil` (field presence is checked structurally there).
    type Deps;

    /// Build the controller core at registration time.
    ///
    /// State-generic controllers construct from the resolved bean graph
    /// (`ctx`); named-state controllers construct from the typed state.
    fn construct(state: &T, ctx: &crate::beans::BeanContext) -> Self;

    /// Build this controller's routes from the resolved application state.
    ///
    /// Generated controllers receive the shared core built by
    /// `register_controller()` and install pre-authentication guards before
    /// state finalization. `ctx` is the resolved bean graph: route decorators
    /// (guards/interceptors, see [`DecoratorSpec`](crate::decorator::DecoratorSpec))
    /// are built from it here, once, and moved into the handler closures.
    fn routes(
        state: &T,
        core: std::sync::Arc<Self>,
        ctx: &crate::beans::BeanContext,
    ) -> crate::http::Router<T>;

    /// Push metadata about this controller's routes into the registry.
    ///
    /// Called by `register_controller()`. The default implementation is a no-op.
    fn register_meta(_registry: &mut crate::meta::MetaRegistry) {}

    /// Register event consumers for this controller.
    ///
    /// Called during `serve()` with the application state and the shared core,
    /// before startup hooks. The default implementation does nothing.
    fn register_consumers(
        _state: T,
        _core: std::sync::Arc<Self>,
    ) -> std::pin::Pin<Box<dyn std::future::Future<Output = ()> + Send>> {
        Box::pin(async {})
    }

    /// Return scheduled task definitions declared via `#[scheduled]`.
    ///
    /// Returns type-erased task definitions. Each task is a
    /// `Box<Box<dyn ScheduledTask>>` wrapped in `Box<dyn Any + Send>`.
    /// This double-boxing allows the scheduler to downcast and start tasks
    /// without knowing the concrete state type.
    ///
    /// The `state` parameter is cloned into each task definition. Every task
    /// execution receives the same shared controller core. `ctx` is the
    /// resolved bean graph: `#[intercept(...)]` sites on scheduled methods are
    /// built from it here, once, exactly like route decorators.
    ///
    /// Called by `register_controller()` to collect tasks automatically.
    /// The default implementation returns an empty list.
    fn scheduled_tasks_boxed(
        state: &T,
        _core: std::sync::Arc<Self>,
        _ctx: &crate::beans::BeanContext,
    ) -> Vec<Box<dyn std::any::Any + Send>> {
        let _ = state;
        Vec::new()
    }

    /// Fill the core's hidden decorator slot from the resolved bean graph.
    ///
    /// Called by `register_controller()` **once**, right after `construct`,
    /// before scheduled tasks are built and before any consumer or direct call
    /// can fire. The generated impl (for controllers whose `#[scheduled]` /
    /// `#[consumer]` methods carry `#[intercept(...)]`) delegates to the core's
    /// [`BeanDecoFill`](crate::decorator::BeanDecoFill) impl; the slot's
    /// `OnceLock` makes the fill first-write-wins, so repeated calls are no-ops.
    /// The default implementation is a no-op (no intercepted transverse methods).
    fn fill_decos(_core: &std::sync::Arc<Self>, _ctx: &crate::beans::BeanContext) {}

    /// Run this controller core's `#[post_construct]` hooks.
    ///
    /// Queued at `register_controller()` and awaited at startup **before**
    /// consumer registrations (mirroring bean `#[post_construct]`, which runs
    /// during `build_state()` before subscribers). The generated impl delegates
    /// to the core's [`PostConstruct`](crate::beans::PostConstruct) impl; the
    /// default returns `Ok(())`. An `Err` fails startup.
    fn post_construct(
        _core: std::sync::Arc<Self>,
    ) -> std::pin::Pin<
        Box<
            dyn std::future::Future<Output = Result<(), Box<dyn std::error::Error + Send + Sync>>>
                + Send,
        >,
    > {
        Box::pin(async { Ok(()) })
    }

    /// Whether this controller declares any `#[pre_destroy]` hook.
    ///
    /// `false` by default; the generated impl sets it to `true` only when the
    /// controller has at least one `#[pre_destroy]` method (i.e. exactly when it
    /// overrides [`pre_destroy`](Self::pre_destroy)). `register_controller()`
    /// reads this to skip queuing a disposer for hook-less controllers, whose
    /// [`pre_destroy`](Self::pre_destroy) is the no-op default.
    const HAS_PRE_DESTROY: bool = false;

    /// Run this controller core's `#[pre_destroy]` disposal hooks.
    ///
    /// Queued at `register_controller()` and awaited during graceful shutdown —
    /// the symmetric counterpart of [`post_construct`](Self::post_construct),
    /// running in the async shutdown phase (before the bean `#[pre_destroy]`
    /// disposers, so a controller disposes before the beans it injected). Controller
    /// cores are not `Clone`, so they cannot impl the `PreDestroy` trait; the
    /// generated override runs the hooks directly from the core `Arc`. An `Err`
    /// is logged and swallowed — disposal never aborts shutdown. The default is
    /// a no-op.
    fn pre_destroy(
        _core: std::sync::Arc<Self>,
    ) -> std::pin::Pin<Box<dyn std::future::Future<Output = ()> + Send>> {
        Box::pin(async {})
    }

    /// Validate all config requirements declared on the controller.
    ///
    /// This covers both `#[config("key")]` individual fields and
    /// `#[config_section]` typed sections. Called automatically by
    /// `register_controller()` when a `R2eConfig` is available.
    /// The default implementation returns an empty list.
    fn validate_config(_config: &crate::config::R2eConfig) -> Vec<crate::config::MissingKeyError> {
        Vec::new()
    }
}
