use std::future::Future;
use std::pin::Pin;

/// Trait for beans that subscribe to events.
///
/// Generated by `#[bean]` when `#[consumer]` methods are present.
/// Each consumer method is wired to its named event bus field via
/// [`EventBus::subscribe`](r2e_events::EventBus::subscribe).
///
/// # Example
///
/// ```ignore
/// #[bean]
/// impl NotificationService {
///     pub fn new(event_bus: LocalEventBus) -> Self {
///         Self { event_bus }
///     }
///
///     #[consumer(bus = "event_bus")]
///     async fn on_user_created(&self, event: Arc<UserCreatedEvent>) {
///         // handle event
///     }
/// }
/// ```
///
/// The macro generates an `EventSubscriber` impl that calls
/// `event_bus.subscribe(...)` for each `#[consumer]` method.
///
/// Register with [`AppBuilder::register_subscriber`]:
///
/// ```ignore
/// AppBuilder::new()
///     .build_state::<Services, _, _>().await
///     .register_subscriber::<NotificationService>()
///     .serve("0.0.0.0:3000").await.unwrap();
/// ```
pub trait EventSubscriber: Clone + Send + Sync + 'static {
    /// Subscribe all consumer methods to their respective event buses.
    fn subscribe(self) -> Pin<Box<dyn Future<Output = ()> + Send>>;
}
