//! Compile-time type-level list for tracking provided bean types.
//!
//! This module implements a type-level linked list that enables the compiler to
//! verify at compile time that all required types have been provided to the
//! [`AppBuilder`](crate::AppBuilder) before calling `build_state()`.
//!
//! # How It Works
//!
//! The type-level list is built using two types:
//! - [`TNil`]: Represents an empty list
//! - [`TCons<H, T>`]: A "cons cell" where `H` is the head type and `T` is the tail
//!
//! When you call `.provide::<T>()` or `.with_bean::<T>()` on the builder, the
//! provision type parameter grows:
//!
//! ```text
//! AppBuilder<NoState, TNil>                    // Initial: empty list
//!     .provide(pool)                           // → AppBuilder<NoState, TCons<Pool, TNil>>
//!     .with_bean::<UserService>()              // → AppBuilder<NoState, TCons<UserService, TCons<Pool, TNil>>>
//! ```
//!
//! # Compile-Time Verification
//!
//! When `build_state::<Services>()` is called, the state's field types (exposed
//! as [`BeanState::Requires`](crate::beans::BeanState::Requires), a `TCons`
//! list generated by `#[derive(BeanState)]`) are folded into the builder's
//! requirement list `R`, and the compiler checks that the whole list satisfies
//! [`AllSatisfied<P, W>`] against the current provision list `P`. `AllSatisfied`
//! walks the requirement list and resolves one [`Contains`] bound per element.
//!
//! If a required type is missing, the compiler produces a clear error message
//! thanks to `#[diagnostic::on_unimplemented]`.
//!
//! # Example
//!
//! ```ignore
//! // This compiles:
//! AppBuilder::new()
//!     .provide(pool)
//!     .with_bean::<UserService>()
//!     .build_state::<Services>()  // ✓ Pool and UserService are both provided
//!     .await
//!
//! // This fails at compile time with a helpful error:
//! AppBuilder::new()
//!     .provide(pool)
//!     .build_state::<Services>()  // ✗ UserService not provided
//!     .await
//! // Error: type `UserService` was not provided to the AppBuilder
//! //        missing `.provide::<UserService>()` or `.with_bean::<UserService>()`
//! ```
//!
//! # Index Witnesses
//!
//! The `Idx` parameter in [`Contains<H, Idx>`] is an "index witness" that tells
//! the compiler where in the list the type was found:
//! - [`Here`]: The type is at the head of the list
//! - [`There<I>`]: The type is somewhere in the tail (recursively)
//!
//! This mechanism avoids overlapping trait implementations and allows the compiler
//! to resolve each `Contains` bound independently.

use std::marker::PhantomData;

/// Empty type-level list.
///
/// Represents a provision list with no types. This is the initial state of
/// `AppBuilder::new()`.
pub struct TNil;

/// Cons cell: `H` is a provided type, `T` is the rest of the list.
///
/// Each call to `.provide::<T>()` or `.with_bean::<T>()` wraps the current
/// list in a new `TCons`:
///
/// ```text
/// TCons<UserService, TCons<Pool, TNil>>
///   │                  │
///   │                  └─ Pool was provided first
///   └─ UserService was provided second
/// ```
///
/// Uses `PhantomData<fn() -> (H, T)>` to avoid imposing `Send`/`Sync`
/// constraints on phantom type parameters.
pub struct TCons<H, T>(PhantomData<fn() -> (H, T)>);

/// Index witness: the element was found at the head of the list.
///
/// Used in `Contains<H, Here>` to indicate that type `H` is the first
/// element of the type-level list.
pub struct Here;

/// Index witness: the element was found somewhere in the tail.
///
/// Used in `Contains<H, There<I>>` to indicate that type `H` is not at
/// the head, but somewhere deeper in the list at index `I`.
pub struct There<T>(PhantomData<fn() -> T>);

/// Compile-time witness that type `H` is present in the type-level list `Self`,
/// located at position `Idx`.
///
/// The `Idx` parameter is an index witness (`Here` or `There<...>`) that guides
/// the compiler's trait resolution and avoids overlapping impls. It is always
/// inferred automatically — users never need to specify it.
///
/// # Trait Implementations
///
/// ```text
/// // Base case: H is at the head
/// impl<H, T> Contains<H, Here> for TCons<H, T> {}
///
/// // Recursive case: H is in the tail
/// impl<H, X, T, I> Contains<H, There<I>> for TCons<X, T>
/// where T: Contains<H, I> {}
/// ```
#[diagnostic::on_unimplemented(
    message = "type `{H}` was not provided to the AppBuilder",
    label = "missing `.provide::<{H}>()` or `.register::<{H}>()`",
    note = "every field type in the BeanState struct must be provided or registered as a bean before calling `build_state()`"
)]
pub trait Contains<H, Idx> {}

// Base case: H is the head of the list.
impl<H, T> Contains<H, Here> for TCons<H, T> {}

// Recursive case: H is somewhere in the tail.
impl<H, X, T, I> Contains<H, There<I>> for TCons<X, T> where T: Contains<H, I> {}

// ── Type-level list concatenation ────────────────────────────────────────

/// Concatenate two type-level lists.
///
/// `TNil ++ Other = Other`, `TCons<H, T> ++ Other = TCons<H, T ++ Other>`.
///
/// Used internally by `AppBuilder` to accumulate bean dependency requirements
/// from multiple bean registrations.
pub trait TAppend<Other> {
    /// The resulting concatenated list.
    type Output;
}

impl<Other> TAppend<Other> for TNil {
    type Output = Other;
}

impl<H, T, Other> TAppend<Other> for TCons<H, T>
where
    T: TAppend<Other>,
{
    type Output = TCons<H, T::Output>;
}

// ── Compile-time requirement verification ────────────────────────────────

/// Compile-time verification that every type in `Self` (the requirements list)
/// is present in the provision list `P`.
///
/// This trait is checked on [`AppBuilder::build_state()`] to ensure that all
/// bean dependencies are satisfied by the current provisions. If a bean
/// declares a dependency that was never `.provide()`-d or registered via
/// `.with_bean()`, the compiler will emit an error at the call site.
///
/// `Indices` is an opaque witness tuple inferred by the compiler.
#[diagnostic::on_unimplemented(
    message = "one or more bean dependencies are missing from the AppBuilder",
    note = "a registered bean has a dependency that was not provided — add `.provide(value)` or `.register::<Type>()` for the missing type"
)]
pub trait AllSatisfied<P, Indices> {}

// Base case: an empty requirements list is always satisfied.
impl<P> AllSatisfied<P, ()> for TNil {}

// Recursive case: the head must be in P, and the tail must also be satisfied.
impl<H, T, P, IH, IT> AllSatisfied<P, (IH, IT)> for TCons<H, T>
where
    P: Contains<H, IH>,
    T: AllSatisfied<P, IT>,
{
}

// ── Plugin dependency resolution ─────────────────────────────────────────

/// Maps a concrete tuple type to a type-level list and resolves values from
/// the bean registry.
///
/// This trait bridges compile-time plugin dependency declarations (`type Deps`)
/// with the type-level provision tracking (`TCons`/`TNil`) and runtime value
/// resolution from [`BeanRegistry`](crate::beans::BeanRegistry).
///
/// # Arity Implementations
///
/// Implementations are provided for tuples of arity 0 through 8:
///
/// | Tuple | Type-level list |
/// |---|---|
/// | `()` | `TNil` |
/// | `(A,)` | `TCons<A, TNil>` |
/// | `(A, B)` | `TCons<A, TCons<B, TNil>>` |
/// | ... | ... |
///
/// # Example
///
/// ```ignore
/// impl PreStatePlugin for MyPlugin {
///     type Provided = MyThing;
///     type Deps = (DbPool, CancellationToken);
///
///     fn install(self, (pool, token): (DbPool, CancellationToken), ctx: &mut PluginInstallContext<'_>) -> MyThing {
///         MyThing::new(pool, token)
///     }
/// }
/// ```
pub trait PluginDeps: Send {
    /// The type-level list representation of these dependencies.
    type AsList;

    /// Resolve all dependency values from the bean registry.
    ///
    /// # Panics
    ///
    /// Panics if a required bean is not present. This should never happen when
    /// the compile-time `AllSatisfied` bound on `.plugin()` is satisfied.
    fn resolve(registry: &crate::beans::BeanRegistry) -> Self;
}

// Arity 0
impl PluginDeps for () {
    type AsList = TNil;

    fn resolve(_registry: &crate::beans::BeanRegistry) -> Self {}
}

macro_rules! impl_plugin_deps {
    ($($T:ident),+) => {
        impl<$($T),+> PluginDeps for ($($T,)+)
        where
            $($T: Clone + Send + Sync + 'static),+
        {
            type AsList = impl_plugin_deps!(@list $($T),+);

            fn resolve(registry: &crate::beans::BeanRegistry) -> Self {
                ($(
                    registry.get_provided::<$T>().cloned()
                        .unwrap_or_else(|| {
                            if registry.is_bean_registered(std::any::TypeId::of::<$T>()) {
                                panic!(
                                    "PluginDeps: bean `{name}` is registered via `.with_bean::<{name}>()` but not \
                                     yet materialized — plugin `Deps` can only reference types supplied via \
                                     `.provide(instance)` at plugin-install time (beans are built later, after all \
                                     plugins install). Change the provider to `.provide(...)` or move the plugin \
                                     install call after the relevant bean has been provided.",
                                    name = std::any::type_name::<$T>()
                                )
                            } else {
                                panic!(
                                    "PluginDeps: bean `{}` not found in registry (this is a bug — the compile-time bound should have caught this)",
                                    std::any::type_name::<$T>()
                                )
                            }
                        }),
                )+)
            }
        }
    };
    (@list $head:ident) => { TCons<$head, TNil> };
    (@list $head:ident, $($rest:ident),+) => { TCons<$head, impl_plugin_deps!(@list $($rest),+)> };
}

impl_plugin_deps!(A);
impl_plugin_deps!(A, B);
impl_plugin_deps!(A, B, C);
impl_plugin_deps!(A, B, C, D);
impl_plugin_deps!(A, B, C, D, E);
impl_plugin_deps!(A, B, C, D, E, F);
impl_plugin_deps!(A, B, C, D, E, F, G);
impl_plugin_deps!(A, B, C, D, E, F, G, H);

/// Registers a tuple of controllers into an [`AppBuilder`](crate::AppBuilder) in
/// one call.
///
/// This backs [`AppBuilder::register_controllers`](crate::AppBuilder::register_controllers),
/// which folds every tuple element through the single-controller
/// `register_controller::<C>()` path, preserving tuple order. Implemented for
/// tuples of arity 1..=16; each element must implement
/// [`Controller<T>`](crate::controller::Controller), so a non-controller in the
/// tuple is a clear compile error.
///
/// ```ignore
/// app.register_controllers::<(UserController, AccountController, DataController)>()
/// ```
pub trait ControllerTuple<T: Clone + Send + Sync + 'static> {
    /// Fold every controller in the tuple through
    /// `register_controller`, in tuple order.
    fn register_all(builder: crate::builder::AppBuilder<T>) -> crate::builder::AppBuilder<T>;
}

macro_rules! impl_controller_tuple {
    ($($C:ident),+) => {
        impl<T, $($C),+> ControllerTuple<T> for ($($C,)+)
        where
            T: Clone + Send + Sync + 'static,
            $($C: crate::controller::Controller<T>),+
        {
            fn register_all(
                builder: crate::builder::AppBuilder<T>,
            ) -> crate::builder::AppBuilder<T> {
                builder
                    $(.register_controller::<$C>())+
            }
        }
    };
}

impl_controller_tuple!(C0);
impl_controller_tuple!(C0, C1);
impl_controller_tuple!(C0, C1, C2);
impl_controller_tuple!(C0, C1, C2, C3);
impl_controller_tuple!(C0, C1, C2, C3, C4);
impl_controller_tuple!(C0, C1, C2, C3, C4, C5);
impl_controller_tuple!(C0, C1, C2, C3, C4, C5, C6);
impl_controller_tuple!(C0, C1, C2, C3, C4, C5, C6, C7);
impl_controller_tuple!(C0, C1, C2, C3, C4, C5, C6, C7, C8);
impl_controller_tuple!(C0, C1, C2, C3, C4, C5, C6, C7, C8, C9);
impl_controller_tuple!(C0, C1, C2, C3, C4, C5, C6, C7, C8, C9, C10);
impl_controller_tuple!(C0, C1, C2, C3, C4, C5, C6, C7, C8, C9, C10, C11);
impl_controller_tuple!(C0, C1, C2, C3, C4, C5, C6, C7, C8, C9, C10, C11, C12);
impl_controller_tuple!(C0, C1, C2, C3, C4, C5, C6, C7, C8, C9, C10, C11, C12, C13);
impl_controller_tuple!(C0, C1, C2, C3, C4, C5, C6, C7, C8, C9, C10, C11, C12, C13, C14);
impl_controller_tuple!(C0, C1, C2, C3, C4, C5, C6, C7, C8, C9, C10, C11, C12, C13, C14, C15);
