//! Compile-time type-level list for tracking provided bean types.
//!
//! This module implements a type-level linked list that enables the compiler to
//! verify at compile time that all required types have been provided to the
//! [`AppBuilder`](crate::AppBuilder) before calling `build_state()`.
//!
//! # How It Works
//!
//! The type-level list is built using two types:
//! - [`TNil`]: Represents an empty list
//! - [`TCons<H, T>`]: A "cons cell" where `H` is the head type and `T` is the tail
//!
//! When you call `.provide::<T>()` or `.register::<T>()` on the builder, the
//! provision type parameter grows:
//!
//! ```text
//! AppBuilder<NoState, TNil>                    // Initial: empty list
//!     .provide(pool)                           // → AppBuilder<NoState, TCons<Pool, TNil>>
//!     .register::<UserService>()              // → AppBuilder<NoState, TCons<UserService, TCons<Pool, TNil>>>
//! ```
//!
//! # Compile-Time Verification
//!
//! When `build_state::<Services>()` is called, the state's field types (exposed
//! as [`BeanState::Requires`](crate::beans::BeanState::Requires), a `TCons`
//! list generated by `#[derive(BeanState)]`) are folded into the builder's
//! requirement list `R`, and the compiler checks that the whole list satisfies
//! [`AllSatisfied<P, W>`] against the current provision list `P`. `AllSatisfied`
//! walks the requirement list and resolves one [`Contains`] bound per element.
//!
//! If a required type is missing, the compiler produces a clear error message
//! thanks to `#[diagnostic::on_unimplemented]`.
//!
//! # Example
//!
//! ```ignore
//! // This compiles:
//! AppBuilder::new()
//!     .provide(pool)
//!     .register::<UserService>()
//!     .build_state::<Services>()  // ✓ Pool and UserService are both provided
//!     .await
//!
//! // This fails at compile time with a helpful error:
//! AppBuilder::new()
//!     .provide(pool)
//!     .build_state::<Services>()  // ✗ UserService not provided
//!     .await
//! // Error: type `UserService` was not provided to the AppBuilder
//! //        missing `.provide::<UserService>()` or `.register::<UserService>()`
//! ```
//!
//! # Index Witnesses
//!
//! The `Idx` parameter in [`Contains<H, Idx>`] is an "index witness" that tells
//! the compiler where in the list the type was found:
//! - [`Here`]: The type is at the head of the list
//! - [`There<I>`]: The type is somewhere in the tail (recursively)
//!
//! This mechanism avoids overlapping trait implementations and allows the compiler
//! to resolve each `Contains` bound independently.

use std::marker::PhantomData;

/// Empty type-level list.
///
/// Represents a provision list with no types. This is the initial state of
/// `AppBuilder::new()`.
pub struct TNil;

/// Cons cell: `H` is a provided type, `T` is the rest of the list.
///
/// Each call to `.provide::<T>()` or `.register::<T>()` wraps the current
/// list in a new `TCons`:
///
/// ```text
/// TCons<UserService, TCons<Pool, TNil>>
///   │                  │
///   │                  └─ Pool was provided first
///   └─ UserService was provided second
/// ```
///
/// Uses `PhantomData<fn() -> (H, T)>` to avoid imposing `Send`/`Sync`
/// constraints on phantom type parameters.
pub struct TCons<H, T>(PhantomData<fn() -> (H, T)>);

/// Index witness: the element was found at the head of the list.
///
/// Used in `Contains<H, Here>` to indicate that type `H` is the first
/// element of the type-level list.
pub struct Here;

/// Index witness: the element was found somewhere in the tail.
///
/// Used in `Contains<H, There<I>>` to indicate that type `H` is not at
/// the head, but somewhere deeper in the list at index `I`.
pub struct There<T>(PhantomData<fn() -> T>);

/// Witness used by `#[derive(BeanState)]` structs: the element is present as a
/// **named field** of a hand-written state struct rather than at a positional
/// slot of an HList.
///
/// Transitional — lets typed-state structs satisfy the same
/// [`Contains`]/[`HasBean`] bounds as HList states while the typed-state path
/// is being phased out.
pub struct ByField;

/// Compile-time witness that type `H` is present in the type-level list `Self`,
/// located at position `Idx`.
///
/// The `Idx` parameter is an index witness (`Here` or `There<...>`) that guides
/// the compiler's trait resolution and avoids overlapping impls. It is always
/// inferred automatically — users never need to specify it.
///
/// # Trait Implementations
///
/// ```text
/// // Base case: H is at the head
/// impl<H, T> Contains<H, Here> for TCons<H, T> {}
///
/// // Recursive case: H is in the tail
/// impl<H, X, T, I> Contains<H, There<I>> for TCons<X, T>
/// where T: Contains<H, I> {}
/// ```
#[diagnostic::on_unimplemented(
    message = "type `{H}` was not provided to the AppBuilder",
    label = "missing `.provide::<{H}>()` or `.register::<{H}>()`",
    note = "every field type in the BeanState struct must be provided or registered as a bean before calling `build_state()`"
)]
pub trait Contains<H, Idx> {}

// Base case: H is the head of the list.
impl<H, T> Contains<H, Here> for TCons<H, T> {}

// Recursive case: H is somewhere in the tail.
impl<H, X, T, I> Contains<H, There<I>> for TCons<X, T> where T: Contains<H, I> {}

// ── Value-level HList (the application state) ────────────────────────────

/// Empty value-level list. The state of an app with no provisions.
///
/// Value-level counterpart of [`TNil`].
#[derive(Clone, Copy, Debug, Default)]
pub struct HNil;

/// Value-level cons cell: `head` is a resolved bean instance, `tail` is the
/// rest of the state.
///
/// Value-level counterpart of [`TCons`]. The application state produced by
/// [`AppBuilder::build_state`](crate::AppBuilder::build_state) is an `HCons`
/// chain whose shape mirrors the builder's provision list `P`, assembled via
/// [`BuildHList`]. Beans are accessed by type through [`HasBean`] /
/// [`BeanAccess::get`], which monomorphize to a fixed-offset field access.
#[derive(Clone, Copy, Debug)]
pub struct HCons<H, T> {
    /// The resolved bean instance at this slot.
    pub head: H,
    /// The rest of the state.
    pub tail: T,
}

/// Compile-time indexed access to a bean of type `T` stored in a value-level
/// HList state.
///
/// `Idx` is an index witness ([`Here`] / [`There`]) that guides trait
/// resolution, exactly like [`Contains`] — it is always inferred, never
/// written by users. Prefer calling [`BeanAccess::get`], which hides the
/// witness entirely: `state.get::<T>()`.
///
/// Resolution monomorphizes to a direct field access (`.tail.tail.head`) —
/// struct-speed, no `TypeId` lookup, hash, or downcast.
#[diagnostic::on_unimplemented(
    message = "bean `{T}` is not present in the application state",
    label = "`{T}` was never provided or registered on the AppBuilder",
    note = "add `.provide(value)` or `.register::<{T}>()` before `build_state()` so the bean is part of the provision list"
)]
pub trait HasBean<T, Idx> {
    /// Clone the bean of type `T` out of the state.
    fn get_bean(&self) -> T;
}

// Base case: T is the head of the list.
impl<H: Clone, Tail> HasBean<H, Here> for HCons<H, Tail> {
    #[inline(always)]
    fn get_bean(&self) -> H {
        self.head.clone()
    }
}

// Recursive case: T is somewhere in the tail.
impl<H, Tail, T, I> HasBean<T, There<I>> for HCons<H, Tail>
where
    Tail: HasBean<T, I>,
{
    #[inline(always)]
    fn get_bean(&self) -> T {
        self.tail.get_bean()
    }
}

/// Witness-free façade over [`HasBean`]: `state.get::<T>()`.
///
/// The index witness lives on the trait (`Idx`) while the bean type lives on
/// the method (`T`), so call sites name only the bean type — the compiler
/// infers `Idx` from the `Self: HasBean<T, Idx>` bound:
///
/// ```ignore
/// let service = state.get::<UserService>();
/// ```
pub trait BeanAccess<Idx> {
    /// Clone the bean of type `T` out of the state.
    fn get<T>(&self) -> T
    where
        Self: HasBean<T, Idx>;
}

impl<S, Idx> BeanAccess<Idx> for S {
    #[inline(always)]
    fn get<T>(&self) -> T
    where
        Self: HasBean<T, Idx>,
    {
        self.get_bean()
    }
}

// `Contains` also holds for the value-level HList, so requirement lists
// (`TCons` chains) can be checked against the materialized state type with the
// same `AllSatisfied` machinery used against the provision list `P`.
impl<H, T> Contains<H, Here> for HCons<H, T> {}
impl<H, X, T, I> Contains<H, There<I>> for HCons<X, T> where T: Contains<H, I> {}

/// Dynamic (`TypeId`-based) bean access over a value-level HList state.
///
/// The witness-free complement of [`HasBean`], for generic code that **cannot
/// carry an index witness**: trait impls where the witness would be an
/// unconstrained impl parameter (E0207) and the concrete implementor type is
/// not nameable by generated code — guard impls
/// (`impl<S: BeanLookup, I> Guard<S, I> for RateLimitGuard`), interceptors,
/// and `ManagedResource` providers like `HasPool`.
///
/// Resolution monomorphizes to a chain of constant `TypeId` comparisons (no
/// hashing, no heap), so a lookup costs at most one integer compare per state
/// slot. Prefer [`HasBean`] / [`BeanAccess::get`] wherever a witness can be
/// threaded — it compiles to a direct field access and turns a missing bean
/// into a compile error, whereas `BeanLookup` reports absence at runtime via
/// `None`.
pub trait BeanLookup {
    /// Borrow the bean with the given `TypeId`, if present.
    fn lookup_bean(&self, tid: std::any::TypeId) -> Option<&(dyn std::any::Any + Send + Sync)>;

    /// Borrow the bean of type `T`, if present.
    fn bean_ref<T: Send + Sync + 'static>(&self) -> Option<&T> {
        self.lookup_bean(std::any::TypeId::of::<T>())?.downcast_ref()
    }

    /// Clone the bean of type `T` out of the state, if present.
    fn bean<T: Clone + Send + Sync + 'static>(&self) -> Option<T> {
        self.bean_ref::<T>().cloned()
    }
}

impl BeanLookup for HNil {
    #[inline(always)]
    fn lookup_bean(&self, _tid: std::any::TypeId) -> Option<&(dyn std::any::Any + Send + Sync)> {
        None
    }
}

impl<H: Send + Sync + 'static, T: BeanLookup> BeanLookup for HCons<H, T> {
    #[inline(always)]
    fn lookup_bean(&self, tid: std::any::TypeId) -> Option<&(dyn std::any::Any + Send + Sync)> {
        if std::any::TypeId::of::<H>() == tid {
            Some(&self.head)
        } else {
            self.tail.lookup_bean(tid)
        }
    }
}

/// Materialize a type-level provision list into a value-level HList state by
/// pulling each slot from the resolved [`BeanContext`](crate::beans::BeanContext).
///
/// Implemented for `TNil` / `TCons` chains. `build_state()` calls this **once
/// at startup** — one `ctx.get::<T>()` (a `TypeId` lookup + clone) per slot —
/// after which all state access is monomorphized field access via [`HasBean`].
pub trait BuildHList {
    /// The value-level HList with the same shape as this type-level list.
    type Output: Clone + Send + Sync + 'static;

    /// Pull every slot from the context, preserving list order.
    ///
    /// # Panics
    ///
    /// Panics if a slot's type is absent from the context. This should never
    /// happen: every type in the provision list `P` was registered or provided
    /// on the builder, and graph resolution fails earlier (with a proper
    /// error) if a bean could not be constructed.
    fn build_hlist(ctx: &crate::beans::BeanContext) -> Self::Output;
}

impl BuildHList for TNil {
    type Output = HNil;

    fn build_hlist(_ctx: &crate::beans::BeanContext) -> HNil {
        HNil
    }
}

impl<H, T> BuildHList for TCons<H, T>
where
    H: Clone + Send + Sync + 'static,
    T: BuildHList,
{
    type Output = HCons<H, T::Output>;

    fn build_hlist(ctx: &crate::beans::BeanContext) -> Self::Output {
        HCons {
            head: ctx.get::<H>(),
            tail: T::build_hlist(ctx),
        }
    }
}

// ── Type-level list concatenation ────────────────────────────────────────

/// Concatenate two type-level lists.
///
/// `TNil ++ Other = Other`, `TCons<H, T> ++ Other = TCons<H, T ++ Other>`.
///
/// Used internally by `AppBuilder` to accumulate bean dependency requirements
/// from multiple bean registrations.
pub trait TAppend<Other> {
    /// The resulting concatenated list.
    type Output;
}

impl<Other> TAppend<Other> for TNil {
    type Output = Other;
}

impl<H, T, Other> TAppend<Other> for TCons<H, T>
where
    T: TAppend<Other>,
{
    type Output = TCons<H, T::Output>;
}

// ── Compile-time requirement verification ────────────────────────────────

/// Compile-time verification that every type in `Self` (the requirements list)
/// is present in the provision list `P`.
///
/// This trait is checked on [`AppBuilder::build_state()`] to ensure that all
/// bean dependencies are satisfied by the current provisions. If a bean
/// declares a dependency that was never `.provide()`-d or registered via
/// `.register()`, the compiler will emit an error at the call site.
///
/// `Indices` is an opaque witness tuple inferred by the compiler.
#[diagnostic::on_unimplemented(
    message = "one or more bean dependencies are missing from the AppBuilder",
    note = "a registered bean has a dependency that was not provided — add `.provide(value)` or `.register::<Type>()` for the missing type"
)]
pub trait AllSatisfied<P, Indices> {}

// Base case: an empty requirements list is always satisfied.
impl<P> AllSatisfied<P, ()> for TNil {}

// Recursive case: the head must be in P, and the tail must also be satisfied.
impl<H, T, P, IH, IT> AllSatisfied<P, (IH, IT)> for TCons<H, T>
where
    P: Contains<H, IH>,
    T: AllSatisfied<P, IT>,
{
}

// ── Plugin dependency resolution ─────────────────────────────────────────

/// Maps a concrete tuple type to a type-level list and resolves values from
/// the bean registry.
///
/// This trait bridges compile-time plugin dependency declarations (`type Deps`)
/// with the type-level provision tracking (`TCons`/`TNil`) and runtime value
/// resolution from [`BeanRegistry`](crate::beans::BeanRegistry).
///
/// # Arity Implementations
///
/// Implementations are provided for tuples of arity 0 through 8:
///
/// | Tuple | Type-level list |
/// |---|---|
/// | `()` | `TNil` |
/// | `(A,)` | `TCons<A, TNil>` |
/// | `(A, B)` | `TCons<A, TCons<B, TNil>>` |
/// | ... | ... |
///
/// # Example
///
/// ```ignore
/// impl PreStatePlugin for MyPlugin {
///     type Provided = MyThing;
///     type Deps = (DbPool, CancellationToken);
///
///     fn install(self, (pool, token): (DbPool, CancellationToken), ctx: &mut PluginInstallContext<'_>) -> MyThing {
///         MyThing::new(pool, token)
///     }
/// }
/// ```
pub trait PluginDeps: Send {
    /// The type-level list representation of these dependencies.
    type AsList;

    /// Resolve all dependency values from the bean registry.
    ///
    /// # Panics
    ///
    /// Panics if a required bean is not present. This should never happen when
    /// the compile-time `AllSatisfied` bound on `.plugin()` is satisfied.
    fn resolve(registry: &crate::beans::BeanRegistry) -> Self;
}

// Arity 0
impl PluginDeps for () {
    type AsList = TNil;

    fn resolve(_registry: &crate::beans::BeanRegistry) -> Self {}
}

macro_rules! impl_plugin_deps {
    ($($T:ident),+) => {
        impl<$($T),+> PluginDeps for ($($T,)+)
        where
            $($T: Clone + Send + Sync + 'static),+
        {
            type AsList = impl_plugin_deps!(@list $($T),+);

            fn resolve(registry: &crate::beans::BeanRegistry) -> Self {
                ($(
                    registry.get_provided::<$T>().cloned()
                        .unwrap_or_else(|| {
                            if registry.is_bean_registered(std::any::TypeId::of::<$T>()) {
                                panic!(
                                    "PluginDeps: bean `{name}` is registered via `.register::<{name}>()` but not \
                                     yet materialized — plugin `Deps` can only reference types supplied via \
                                     `.provide(instance)` at plugin-install time (beans are built later, after all \
                                     plugins install). Change the provider to `.provide(...)` or move the plugin \
                                     install call after the relevant bean has been provided.",
                                    name = std::any::type_name::<$T>()
                                )
                            } else {
                                panic!(
                                    "PluginDeps: bean `{}` not found in registry (this is a bug — the compile-time bound should have caught this)",
                                    std::any::type_name::<$T>()
                                )
                            }
                        }),
                )+)
            }
        }
    };
    (@list $head:ident) => { TCons<$head, TNil> };
    (@list $head:ident, $($rest:ident),+) => { TCons<$head, impl_plugin_deps!(@list $($rest),+)> };
}

impl_plugin_deps!(A);
impl_plugin_deps!(A, B);
impl_plugin_deps!(A, B, C);
impl_plugin_deps!(A, B, C, D);
impl_plugin_deps!(A, B, C, D, E);
impl_plugin_deps!(A, B, C, D, E, F);
impl_plugin_deps!(A, B, C, D, E, F, G);
impl_plugin_deps!(A, B, C, D, E, F, G, H);

/// Registers a tuple of controllers into an [`AppBuilder`](crate::AppBuilder) in
/// one call.
///
/// This backs
/// [`RegisterControllers::register_controllers`](crate::builder::RegisterControllers::register_controllers),
/// which folds every tuple element through the single-controller registration
/// path, preserving tuple order. Implemented for tuples of arity 1..=16; each
/// element must implement [`Controller<T, Wi>`](crate::controller::Controller)
/// with its dependency list satisfied by the state, so a non-controller in the
/// tuple — or a controller with a missing bean — is a clear compile error.
///
/// `W` collects one `(Wi, Di)` witness pair per element (extraction markers +
/// dependency indices); it is always inferred.
///
/// ```ignore
/// app.register_controllers::<(UserController, AccountController, DataController)>()
/// ```
pub trait ControllerTuple<T: Clone + Send + Sync + 'static, W> {
    /// Fold every controller in the tuple through
    /// `register_controller`, in tuple order.
    fn register_all(builder: crate::builder::AppBuilder<T>) -> crate::builder::AppBuilder<T>;
}

macro_rules! impl_controller_tuple {
    ($(($C:ident, $W:ident, $D:ident)),+) => {
        impl<T, $($C, $W, $D),+> ControllerTuple<T, ($(($W, $D),)+)> for ($($C,)+)
        where
            T: Clone + Send + Sync + 'static,
            $(
                $C: crate::controller::Controller<T, $W>,
                <$C as crate::controller::Controller<T, $W>>::Deps: AllSatisfied<T, $D>,
            )+
        {
            fn register_all(
                builder: crate::builder::AppBuilder<T>,
            ) -> crate::builder::AppBuilder<T> {
                builder
                    $(.register_controller_impl::<$C, $W, $D>())+
            }
        }
    };
}

impl_controller_tuple!((C0, W0, D0));
impl_controller_tuple!((C0, W0, D0), (C1, W1, D1));
impl_controller_tuple!((C0, W0, D0), (C1, W1, D1), (C2, W2, D2));
impl_controller_tuple!((C0, W0, D0), (C1, W1, D1), (C2, W2, D2), (C3, W3, D3));
impl_controller_tuple!((C0, W0, D0), (C1, W1, D1), (C2, W2, D2), (C3, W3, D3), (C4, W4, D4));
impl_controller_tuple!(
    (C0, W0, D0),
    (C1, W1, D1),
    (C2, W2, D2),
    (C3, W3, D3),
    (C4, W4, D4),
    (C5, W5, D5)
);
impl_controller_tuple!(
    (C0, W0, D0),
    (C1, W1, D1),
    (C2, W2, D2),
    (C3, W3, D3),
    (C4, W4, D4),
    (C5, W5, D5),
    (C6, W6, D6)
);
impl_controller_tuple!(
    (C0, W0, D0),
    (C1, W1, D1),
    (C2, W2, D2),
    (C3, W3, D3),
    (C4, W4, D4),
    (C5, W5, D5),
    (C6, W6, D6),
    (C7, W7, D7)
);
impl_controller_tuple!(
    (C0, W0, D0),
    (C1, W1, D1),
    (C2, W2, D2),
    (C3, W3, D3),
    (C4, W4, D4),
    (C5, W5, D5),
    (C6, W6, D6),
    (C7, W7, D7),
    (C8, W8, D8)
);
impl_controller_tuple!(
    (C0, W0, D0),
    (C1, W1, D1),
    (C2, W2, D2),
    (C3, W3, D3),
    (C4, W4, D4),
    (C5, W5, D5),
    (C6, W6, D6),
    (C7, W7, D7),
    (C8, W8, D8),
    (C9, W9, D9)
);
impl_controller_tuple!(
    (C0, W0, D0),
    (C1, W1, D1),
    (C2, W2, D2),
    (C3, W3, D3),
    (C4, W4, D4),
    (C5, W5, D5),
    (C6, W6, D6),
    (C7, W7, D7),
    (C8, W8, D8),
    (C9, W9, D9),
    (C10, W10, D10)
);
impl_controller_tuple!(
    (C0, W0, D0),
    (C1, W1, D1),
    (C2, W2, D2),
    (C3, W3, D3),
    (C4, W4, D4),
    (C5, W5, D5),
    (C6, W6, D6),
    (C7, W7, D7),
    (C8, W8, D8),
    (C9, W9, D9),
    (C10, W10, D10),
    (C11, W11, D11)
);
impl_controller_tuple!(
    (C0, W0, D0),
    (C1, W1, D1),
    (C2, W2, D2),
    (C3, W3, D3),
    (C4, W4, D4),
    (C5, W5, D5),
    (C6, W6, D6),
    (C7, W7, D7),
    (C8, W8, D8),
    (C9, W9, D9),
    (C10, W10, D10),
    (C11, W11, D11),
    (C12, W12, D12)
);
impl_controller_tuple!(
    (C0, W0, D0),
    (C1, W1, D1),
    (C2, W2, D2),
    (C3, W3, D3),
    (C4, W4, D4),
    (C5, W5, D5),
    (C6, W6, D6),
    (C7, W7, D7),
    (C8, W8, D8),
    (C9, W9, D9),
    (C10, W10, D10),
    (C11, W11, D11),
    (C12, W12, D12),
    (C13, W13, D13)
);
impl_controller_tuple!(
    (C0, W0, D0),
    (C1, W1, D1),
    (C2, W2, D2),
    (C3, W3, D3),
    (C4, W4, D4),
    (C5, W5, D5),
    (C6, W6, D6),
    (C7, W7, D7),
    (C8, W8, D8),
    (C9, W9, D9),
    (C10, W10, D10),
    (C11, W11, D11),
    (C12, W12, D12),
    (C13, W13, D13),
    (C14, W14, D14)
);
impl_controller_tuple!(
    (C0, W0, D0),
    (C1, W1, D1),
    (C2, W2, D2),
    (C3, W3, D3),
    (C4, W4, D4),
    (C5, W5, D5),
    (C6, W6, D6),
    (C7, W7, D7),
    (C8, W8, D8),
    (C9, W9, D9),
    (C10, W10, D10),
    (C11, W11, D11),
    (C12, W12, D12),
    (C13, W13, D13),
    (C14, W14, D14),
    (C15, W15, D15)
);
